(() => {
  "use strict";
  const DATA = window.FV_MEDIATHEQUE_DATA || (window.FV_MEDIATHEQUE_DATA = { resources: [], dossiers: [] });
  if (!Array.isArray(DATA.resources)) DATA.resources = [];
  const incoming = [
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-clinique-cm01-02-introduction-generale-de-la-clinique",
    "slug": "cm01-02-introduction-generale-de-la-clinique.md",
    "title": "CM01-02 — Introduction générale de la clinique",
    "module": "CM — Psychologie clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 1,
    "description": "La psychologie à une histoire particulière et à plusieurs champs",
    "themes": [
      "Psychologie clinique",
      "Psychopathologie"
    ],
    "keywords": [
      "CM01-02 — Introduction générale de la clinique",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE CLINIQUE/CM01-02 - Introduction générale de la clinique.docx",
      "CM — Psychologie clinique",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-clinique/cm01-02-introduction-generale-de-la-clinique.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-clinique-cm01-02-introduction-generale-de-la-clinique"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-clinique-cm01-introduction-generale-de-la-clinique",
    "slug": "cm01-introduction-generale-de-la-clinique.md",
    "title": "CM01 — Introduction générale de la clinique",
    "module": "CM — Psychologie clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 2,
    "description": "La psychologie à une histoire particulière et à plusieurs champs",
    "themes": [
      "Psychologie clinique",
      "Psychopathologie"
    ],
    "keywords": [
      "CM01 — Introduction générale de la clinique",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE CLINIQUE/CM01 - Introduction générale de la clinique.docx",
      "CM — Psychologie clinique",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-clinique/cm01-introduction-generale-de-la-clinique.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-clinique-cm01-introduction-generale-de-la-clinique"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-clinique-cm03-le-courant-clinique-et-pathologique",
    "slug": "cm03-le-courant-clinique-et-pathologique.md",
    "title": "CM03 — Le courant clinique et pathologique",
    "module": "CM — Psychologie clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 3,
    "description": "La clinique va d’abord être dans la rencontre d’un patient. On va élaborer les hypothèses à travers cette rencontre avec le patient. On va théoriser comme cela. Souvent, le stage en de la formation de psychologie va nous diriger vers l’exercice qu’on va faire…",
    "themes": [
      "Psychologie clinique",
      "Psychopathologie"
    ],
    "keywords": [
      "CM03 — Le courant clinique et pathologique",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE CLINIQUE/CM03 - Le courant clinique et pathologique.docx",
      "CM — Psychologie clinique",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-clinique/cm03-le-courant-clinique-et-pathologique.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-clinique-cm03-le-courant-clinique-et-pathologique"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-clinique-cm04-les-organisations-psychotiques-le-dsm",
    "slug": "cm04-les-organisations-psychotiques-le-dsm.md",
    "title": "CM04 — Les organisations psychotiques & le DSM",
    "module": "CM — Psychologie clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 4,
    "description": "Les psychoses sont les maladies les plus graves. Elle correspond à l’image de la folie. Il n’y a pas la psychose, il y a les psychoses",
    "themes": [
      "Psychologie clinique",
      "Psychopathologie"
    ],
    "keywords": [
      "CM04 — Les organisations psychotiques & le DSM",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE CLINIQUE/CM04 - Les organisations psychotiques & le DSM.docx",
      "CM — Psychologie clinique",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-clinique/cm04-les-organisations-psychotiques-le-dsm.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-clinique-cm04-les-organisations-psychotiques-le-dsm"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-clinique-cm05-la-resilience-et-differents-etat-aigus",
    "slug": "cm05-la-resilience-et-differents-etat-aigus.md",
    "title": "CM05 — La résilience et différents état aigus",
    "module": "CM — Psychologie clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 5,
    "description": "La résilience est l’équivalent de « copyng ». C’est la capacité de rebondir. C’est une notion empruntée à la marine (avec la résistance aux chocs). En psychopathologie, c’est :",
    "themes": [
      "Psychologie clinique",
      "Psychopathologie",
      "Résilience"
    ],
    "keywords": [
      "CM05 — La résilience et différents état aigus",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE CLINIQUE/CM05 - La résilience et différents état aigus.docx",
      "CM — Psychologie clinique",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-clinique/cm05-la-resilience-et-differents-etat-aigus.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-clinique-cm05-la-resilience-et-differents-etat-aigus"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-clinique-cm06-le-courant-humaniste",
    "slug": "cm06-le-courant-humaniste.md",
    "title": "CM06 — Le courant humaniste",
    "module": "CM — Psychologie clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 6,
    "description": "C’est un courant psychologique assez récent qui met l’Homme et ses valeurs au-dessus de toutes les autres valeurs et affirme l’impossibilité d’élaborer un savoir théorique général sur le fonctionnement psychologique en considérant la personne comme une totalit…",
    "themes": [
      "Psychologie clinique",
      "Psychopathologie"
    ],
    "keywords": [
      "CM06 — Le courant humaniste",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE CLINIQUE/CM06 - Le courant humaniste.docx",
      "CM — Psychologie clinique",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-clinique/cm06-le-courant-humaniste.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-clinique-cm06-le-courant-humaniste"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-clinique-cm07-08-les-therapies-familiales",
    "slug": "cm07-08-les-therapies-familiales.md",
    "title": "CM07-08 — Les thérapies familiales",
    "module": "CM — Psychologie clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 7,
    "description": "L’origine des thérapies familiales est différente en fonction des modèles thérapeutiques. Pour essayer de résumer, on trouve plusieurs courants qui développent des approches familiales pour lesquels les théories, les moyens et les dispositifs sont très différe…",
    "themes": [
      "Psychologie clinique",
      "Psychopathologie"
    ],
    "keywords": [
      "CM07-08 — Les thérapies familiales",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE CLINIQUE/CM07-08 - Les thérapies familiales.docx",
      "CM — Psychologie clinique",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-clinique/cm07-08-les-therapies-familiales.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-clinique-cm07-08-les-therapies-familiales"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-clinique-cmv2-01-02-les-grands-courants-en-psychologie-clinique",
    "slug": "cmv2-01-02-les-grands-courants-en-psychologie-clinique.md",
    "title": "CMV2 — 01-02 — Les grands courants en psychologie clinique",
    "module": "CM — Psychologie clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 8,
    "description": "La psychologie à une histoire particulière et à plusieurs champs",
    "themes": [
      "Psychologie clinique",
      "Psychopathologie"
    ],
    "keywords": [
      "CMV2 — 01-02 — Les grands courants en psychologie clinique",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE CLINIQUE/CMV2 - 01-02 - Les grands courants en psychologie clinique.docx",
      "CM — Psychologie clinique",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-clinique/cmv2-01-02-les-grands-courants-en-psychologie-clinique.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-clinique-cmv2-01-02-les-grands-courants-en-psychologie-clinique"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-clinique-cmv2-03-05-le-courant-clinique-et-pathologique",
    "slug": "cmv2-03-05-le-courant-clinique-et-pathologique.md",
    "title": "CMV2 — 03-05 — Le courant clinique et pathologique",
    "module": "CM — Psychologie clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 9,
    "description": "Perspectives sociohistoriques, épistémologiques, méthodologiques et thérapeutiques",
    "themes": [
      "Psychologie clinique",
      "Psychopathologie"
    ],
    "keywords": [
      "CMV2 — 03-05 — Le courant clinique et pathologique",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE CLINIQUE/CMV2 - 03-05 - Le courant clinique et pathologique.docx",
      "CM — Psychologie clinique",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-clinique/cmv2-03-05-le-courant-clinique-et-pathologique.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-clinique-cmv2-03-05-le-courant-clinique-et-pathologique"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-cognitive-cm01-02-l-emergence-de-la-psychologie-cognitive",
    "slug": "cm01-02-l-emergence-de-la-psychologie-cognitive.md",
    "title": "CM01-02 — L émergence de la psychologie cognitive",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 1,
    "description": "Un des premiers travaux qui a permis de dépasser le concept de la boite noire est le travail de Norbert Wiener (1894-1964) et la cybernétique. On va ainsi avoir un concept de but et de rétroaction",
    "themes": [
      "Psychologie cognitive",
      "Cognition"
    ],
    "keywords": [
      "CM01-02 — L émergence de la psychologie cognitive",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE COGNITIVE/CM01-02 - L émergence de la psychologie cognitive.docx",
      "CM — Psychologie cognitive",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-cognitive/cm01-02-l-emergence-de-la-psychologie-cognitive.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-cognitive-cm01-02-l-emergence-de-la-psychologie-cognitive"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-cognitive-cm01-fondements-philosophiques-de-la-psychologie-cognitive",
    "slug": "cm01-fondements-philosophiques-de-la-psychologie-cognitive.md",
    "title": "CM01 — Fondements philosophiques de la psychologie cognitive",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 2,
    "description": "Fondements philosophiques de la psychologie cognitive",
    "themes": [
      "Psychologie cognitive",
      "Cognition"
    ],
    "keywords": [
      "CM01 — Fondements philosophiques de la psychologie cognitive",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE COGNITIVE/CM01 - Fondements philosophiques de la psychologie cognitive.docx",
      "CM — Psychologie cognitive",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-cognitive/cm01-fondements-philosophiques-de-la-psychologie-cognitive.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-cognitive-cm01-fondements-philosophiques-de-la-psychologie-cognitive"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-cognitive-cm03-fondement-theoriques-de-la-methode-experimentale-scientifique",
    "slug": "cm03-fondement-theoriques-de-la-methode-experimentale-scientifique.md",
    "title": "CM03 — Fondement théoriques de la méthode expérimentale scientifique",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 3,
    "description": "La méthode expérimentale se base sur 2 postulats :",
    "themes": [
      "Psychologie cognitive",
      "Cognition"
    ],
    "keywords": [
      "CM03 — Fondement théoriques de la méthode expérimentale scientifique",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE COGNITIVE/CM03 - Fondement théoriques de la méthode expérimentale scientifique.docx",
      "CM — Psychologie cognitive",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-cognitive/cm03-fondement-theoriques-de-la-methode-experimentale-scientifique.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-cognitive-cm03-fondement-theoriques-de-la-methode-experimentale-scientifique"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-cognitive-cm04-06-application-de-la-methode-hypothetico-deductive-a-la-psychologie",
    "slug": "cm04-06-application-de-la-methode-hypothetico-deductive-a-la-psychologie.md",
    "title": "CM04-06 — Application de la méthode hypothético-déductive à la psychologie",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 4,
    "description": "Nous avons deux niveaux d’hypothèse pour la démarche expérimentale :",
    "themes": [
      "Psychologie cognitive",
      "Cognition"
    ],
    "keywords": [
      "CM04-06 — Application de la méthode hypothético-déductive à la psychologie",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE COGNITIVE/CM04-06 - Application de la méthode hypothético-déductive à la psychologie.docx",
      "CM — Psychologie cognitive",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-cognitive/cm04-06-application-de-la-methode-hypothetico-deductive-a-la-psychologie.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-cognitive-cm04-06-application-de-la-methode-hypothetico-deductive-a-la-psychologie"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-cognitive-cm06-07-neuroscience-et-psychologie-cognitive",
    "slug": "cm06-07-neuroscience-et-psychologie-cognitive.md",
    "title": "CM06-07 — Neuroscience et psychologie cognitive",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 5,
    "description": "CHAPITRE IV : neuroscience et psychologie cognitive",
    "themes": [
      "Psychologie cognitive",
      "Cognition"
    ],
    "keywords": [
      "CM06-07 — Neuroscience et psychologie cognitive",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE COGNITIVE/CM06-07 - Neuroscience et psychologie cognitive.docx",
      "CM — Psychologie cognitive",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-cognitive/cm06-07-neuroscience-et-psychologie-cognitive.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-cognitive-cm06-07-neuroscience-et-psychologie-cognitive"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-cognitive-cm07b-08-de-la-perception-a-la-cognition-exemple-de-la-categorisation-perceptive",
    "slug": "cm07b-08-de-la-perception-a-la-cognition-exemple-de-la-categorisation-perceptive.md",
    "title": "CM07B-08 — De la perception à la cognition (exemple de la catégorisation perceptive)",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 6,
    "description": "De la perception à la cognition L’exemple de la catégorisation perceptive",
    "themes": [
      "Psychologie cognitive",
      "Cognition",
      "Perception"
    ],
    "keywords": [
      "CM07B-08 — De la perception à la cognition (exemple de la catégorisation perceptive)",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE COGNITIVE/CM07B-08 - De la perception à la cognition (exemple de la catégorisation perceptive).docx",
      "CM — Psychologie cognitive",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-cognitive/cm07b-08-de-la-perception-a-la-cognition-exemple-de-la-categorisation-perceptive.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-cognitive-cm07b-08-de-la-perception-a-la-cognition-exemple-de-la-categorisation-perceptive"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-cognitive-cm07a-la-perception-application-de-la-methode-experimentale-en-psychophysique",
    "slug": "cm07a-la-perception-application-de-la-methode-experimentale-en-psychophysique.md",
    "title": "CM07A — La perception — application de la méthode expérimentale en psychophysique",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 7,
    "description": "Application de la méthode expérimentale en psychophysique",
    "themes": [
      "Psychologie cognitive",
      "Cognition",
      "Perception"
    ],
    "keywords": [
      "CM07A — La perception — application de la méthode expérimentale en psychophysique",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE COGNITIVE/CM07A - La perception - application de la méthode expérimentale en psychophysique.docx",
      "CM — Psychologie cognitive",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-cognitive/cm07a-la-perception-application-de-la-methode-experimentale-en-psychophysique.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-cognitive-cm07a-la-perception-application-de-la-methode-experimentale-en-psychophysique"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-cognitive-cm08b-les-bases-neurales-et-computationnelles-de-la-cognition",
    "slug": "cm08b-les-bases-neurales-et-computationnelles-de-la-cognition.md",
    "title": "CM08B — Les bases neurales et computationnelles de la cognition",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 8,
    "description": "Les bases neurales et computationnelles de la cognition",
    "themes": [
      "Psychologie cognitive",
      "Cognition"
    ],
    "keywords": [
      "CM08B — Les bases neurales et computationnelles de la cognition",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE COGNITIVE/CM08B - Les bases neurales et computationnelles de la cognition.docx",
      "CM — Psychologie cognitive",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-cognitive/cm08b-les-bases-neurales-et-computationnelles-de-la-cognition.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-cognitive-cm08b-les-bases-neurales-et-computationnelles-de-la-cognition"
  },
  {
    "id": "cours:psy-l1-s2-ue1-psychologie-cognitive-cm08c-concept-de-systeme-localiste-versus-parallele-distribue",
    "slug": "cm08c-concept-de-systeme-localiste-versus-parallele-distribue.md",
    "title": "CM08C- Concept de système localiste versus parallèle distribué",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 9,
    "description": "On va avoir des critiques sur les systèmes de neurones et théories",
    "themes": [
      "Psychologie cognitive",
      "Cognition"
    ],
    "keywords": [
      "CM08C- Concept de système localiste versus parallèle distribué",
      "UE1 - COGNITIVE & CLINIQUE/PSYCHOLOGIE COGNITIVE/CM08C- Concept de système localiste versus parallèle distribué.docx",
      "CM — Psychologie cognitive",
      "UE1 — Psychologie cognitive & clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE1 — Psychologie cognitive & clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue1/psychologie-cognitive/cm08c-concept-de-systeme-localiste-versus-parallele-distribue.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue1-psychologie-cognitive-cm08c-concept-de-systeme-localiste-versus-parallele-distribue"
  },
  {
    "id": "cours:psy-l1-s2-ue2-bases-de-biologie-cm01-02-chimie-du-vivant",
    "slug": "cm01-02-chimie-du-vivant.md",
    "title": "CM01-02 — Chimie du vivant",
    "module": "CM — Bases de biologie",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 1,
    "description": "Formation des molécules : les liaisons chimiques",
    "themes": [
      "Biologie",
      "Neurosciences"
    ],
    "keywords": [
      "CM01-02 — Chimie du vivant",
      "UE2 - SOCIALE & BIOLOGIE/BASES BIOLOGIE/CM01-02 - Chimie du vivant.docx",
      "CM — Bases de biologie",
      "UE2 — Psychologie sociale & bases biologiques",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE2 — Psychologie sociale & bases biologiques",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Bases de biologie",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue2/bases-de-biologie/cm01-02-chimie-du-vivant.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue2-bases-de-biologie-cm01-02-chimie-du-vivant"
  },
  {
    "id": "cours:psy-l1-s2-ue2-bases-de-biologie-cm01-quest-ce-que-le-vivant",
    "slug": "cm01-quest-ce-que-le-vivant.md",
    "title": "CM01- Qu’est-ce que le vivant",
    "module": "CM — Bases de biologie",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 2,
    "description": "Les différents niveaux d’intégration du vivant",
    "themes": [
      "Biologie",
      "Neurosciences"
    ],
    "keywords": [
      "CM01- Qu’est-ce que le vivant",
      "UE2 - SOCIALE & BIOLOGIE/BASES BIOLOGIE/CM01- Qu’est-ce que le vivant.docx",
      "CM — Bases de biologie",
      "UE2 — Psychologie sociale & bases biologiques",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE2 — Psychologie sociale & bases biologiques",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Bases de biologie",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue2/bases-de-biologie/cm01-quest-ce-que-le-vivant.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue2-bases-de-biologie-cm01-quest-ce-que-le-vivant"
  },
  {
    "id": "cours:psy-l1-s2-ue2-bases-de-biologie-cm04-05-l-information-genetique-partie-1",
    "slug": "cm04-05-l-information-genetique-partie-1.md",
    "title": "CM04-05 — L information génétique — Partie 1",
    "module": "CM — Bases de biologie",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 3,
    "description": "Le génome et l’expression de l’information génétique",
    "themes": [
      "Biologie",
      "Neurosciences",
      "Génétique"
    ],
    "keywords": [
      "CM04-05 — L information génétique — Partie 1",
      "UE2 - SOCIALE & BIOLOGIE/BASES BIOLOGIE/CM04-05 - L information génétique - Partie 1.docx",
      "CM — Bases de biologie",
      "UE2 — Psychologie sociale & bases biologiques",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE2 — Psychologie sociale & bases biologiques",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Bases de biologie",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue2/bases-de-biologie/cm04-05-l-information-genetique-partie-1.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue2-bases-de-biologie-cm04-05-l-information-genetique-partie-1"
  },
  {
    "id": "cours:psy-l1-s2-ue2-bases-de-biologie-cm05-07-l-information-genetique-partie-2",
    "slug": "cm05-07-l-information-genetique-partie-2.md",
    "title": "CM05-07 — L information génétique — Partie 2",
    "module": "CM — Bases de biologie",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 4,
    "description": "On va dupliquer la molécule d’ADN mère (dans le noyau)",
    "themes": [
      "Biologie",
      "Neurosciences",
      "Génétique"
    ],
    "keywords": [
      "CM05-07 — L information génétique — Partie 2",
      "UE2 - SOCIALE & BIOLOGIE/BASES BIOLOGIE/CM05-07 - L information génétique - Partie 2.docx",
      "CM — Bases de biologie",
      "UE2 — Psychologie sociale & bases biologiques",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE2 — Psychologie sociale & bases biologiques",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Bases de biologie",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue2/bases-de-biologie/cm05-07-l-information-genetique-partie-2.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue2-bases-de-biologie-cm05-07-l-information-genetique-partie-2"
  },
  {
    "id": "cours:psy-l1-s2-ue2-bases-de-biologie-cm07-08-cellules-du-systeme-nerveux",
    "slug": "cm07-08-cellules-du-systeme-nerveux.md",
    "title": "CM07-08 — Cellules du système nerveux",
    "module": "CM — Bases de biologie",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 5,
    "description": "Les neurones ont le rôle de réception, d’intégration et de transmission sous forme de signal électrique. Ces réceptions vont être de différentes natures",
    "themes": [
      "Biologie",
      "Neurosciences"
    ],
    "keywords": [
      "CM07-08 — Cellules du système nerveux",
      "UE2 - SOCIALE & BIOLOGIE/BASES BIOLOGIE/CM07-08 - Cellules du système nerveux.docx",
      "CM — Bases de biologie",
      "UE2 — Psychologie sociale & bases biologiques",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE2 — Psychologie sociale & bases biologiques",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Bases de biologie",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue2/bases-de-biologie/cm07-08-cellules-du-systeme-nerveux.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue2-bases-de-biologie-cm07-08-cellules-du-systeme-nerveux"
  },
  {
    "id": "cours:psy-l1-s2-ue2-bases-de-biologie-cm07-introduction-subdivision-du-systeme-nerveux",
    "slug": "cm07-introduction-subdivision-du-systeme-nerveux.md",
    "title": "CM07 — Introduction — Subdivision du système nerveux",
    "module": "CM — Bases de biologie",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 6,
    "description": "Introduction – Subdivisons du système nerveux",
    "themes": [
      "Biologie",
      "Neurosciences"
    ],
    "keywords": [
      "CM07 — Introduction — Subdivision du système nerveux",
      "UE2 - SOCIALE & BIOLOGIE/BASES BIOLOGIE/CM07 - Introduction - Subdivision du système nerveux.docx",
      "CM — Bases de biologie",
      "UE2 — Psychologie sociale & bases biologiques",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE2 — Psychologie sociale & bases biologiques",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Bases de biologie",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue2/bases-de-biologie/cm07-introduction-subdivision-du-systeme-nerveux.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue2-bases-de-biologie-cm07-introduction-subdivision-du-systeme-nerveux"
  },
  {
    "id": "cours:psy-l1-s2-ue2-bases-de-biologie-cm08-09-physiologie-neuronale",
    "slug": "cm08-09-physiologie-neuronale.md",
    "title": "CM08-09 — Physiologie neuronale",
    "module": "CM — Bases de biologie",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 7,
    "description": "Potentiel membranaire au repos : potentiel de repos",
    "themes": [
      "Biologie",
      "Neurosciences"
    ],
    "keywords": [
      "CM08-09 — Physiologie neuronale",
      "UE2 - SOCIALE & BIOLOGIE/BASES BIOLOGIE/CM08-09 - Physiologie neuronale.docx",
      "CM — Bases de biologie",
      "UE2 — Psychologie sociale & bases biologiques",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE2 — Psychologie sociale & bases biologiques",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Bases de biologie",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue2/bases-de-biologie/cm08-09-physiologie-neuronale.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue2-bases-de-biologie-cm08-09-physiologie-neuronale"
  },
  {
    "id": "cours:psy-l1-s2-ue2-psychologie-sociale-cm01-05-la-psychologie-de-la-religion-une-discipline-academique",
    "slug": "cm01-05-la-psychologie-de-la-religion-une-discipline-academique.md",
    "title": "CM01-05 — La psychologie de la religion — Une discipline académique",
    "module": "CM — Psychologie sociale",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 1,
    "description": "Intérêt de l’étude du fait religieux pour le psychologue",
    "themes": [
      "Psychologie sociale",
      "Religion"
    ],
    "keywords": [
      "CM01-05 — La psychologie de la religion — Une discipline académique",
      "UE2 - SOCIALE & BIOLOGIE/PSYCHOLOGIE SOCIALE/CM01-05 - La psychologie de la religion - Une discipline académique.docx",
      "CM — Psychologie sociale",
      "UE2 — Psychologie sociale & bases biologiques",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE2 — Psychologie sociale & bases biologiques",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie sociale",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue2/psychologie-sociale/cm01-05-la-psychologie-de-la-religion-une-discipline-academique.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue2-psychologie-sociale-cm01-05-la-psychologie-de-la-religion-une-discipline-academique"
  },
  {
    "id": "cours:psy-l1-s2-ue2-psychologie-sociale-cm05-mesurer-la-religiosite-definir-la-religion",
    "slug": "cm05-mesurer-la-religiosite-definir-la-religion.md",
    "title": "CM05 — Mesurer la Religiosité, définir la Religion",
    "module": "CM — Psychologie sociale",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 2,
    "description": "On peut commencer par vouloir connaitre le pourcentage de la population française qui sont religieux, ou les étudiants de première année de psychologie",
    "themes": [
      "Psychologie sociale",
      "Religion"
    ],
    "keywords": [
      "CM05 — Mesurer la Religiosité, définir la Religion",
      "UE2 - SOCIALE & BIOLOGIE/PSYCHOLOGIE SOCIALE/CM05 - Mesurer la Religiosité, définir la Religion.docx",
      "CM — Psychologie sociale",
      "UE2 — Psychologie sociale & bases biologiques",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE2 — Psychologie sociale & bases biologiques",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie sociale",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue2/psychologie-sociale/cm05-mesurer-la-religiosite-definir-la-religion.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue2-psychologie-sociale-cm05-mesurer-la-religiosite-definir-la-religion"
  },
  {
    "id": "cours:psy-l1-s2-ue3-psychologie-de-ladolescent-cm01-du-concept-de-jeunesse-au-concept-dadolescence",
    "slug": "cm01-du-concept-de-jeunesse-au-concept-dadolescence.md",
    "title": "CM01 — Du concept de jeunesse au concept d’adolescence",
    "module": "CM — Psychologie de l’adolescent",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 1,
    "description": "Du concept de jeunesse au concept d’adolescence",
    "themes": [
      "Psychologie du développement",
      "Adolescence"
    ],
    "keywords": [
      "CM01 — Du concept de jeunesse au concept d’adolescence",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/PSYCHOLOGIE DE L ADOLESCENT/CM01 - Du concept de jeunesse au concept d’adolescence.docx",
      "CM — Psychologie de l’adolescent",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/psychologie-de-ladolescent/cm01-du-concept-de-jeunesse-au-concept-dadolescence.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-psychologie-de-ladolescent-cm01-du-concept-de-jeunesse-au-concept-dadolescence"
  },
  {
    "id": "cours:psy-l1-s2-ue3-psychologie-de-ladolescent-cm02-puberte-nutrition-sommeil",
    "slug": "cm02-puberte-nutrition-sommeil.md",
    "title": "CM02 — Puberté, nutrition & sommeil",
    "module": "CM — Psychologie de l’adolescent",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 2,
    "description": "Puberté, changement physiques & physiologiques",
    "themes": [
      "Psychologie du développement",
      "Adolescence"
    ],
    "keywords": [
      "CM02 — Puberté, nutrition & sommeil",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/PSYCHOLOGIE DE L ADOLESCENT/CM02 - Puberté, nutrition & sommeil.docx",
      "CM — Psychologie de l’adolescent",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/psychologie-de-ladolescent/cm02-puberte-nutrition-sommeil.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-psychologie-de-ladolescent-cm02-puberte-nutrition-sommeil"
  },
  {
    "id": "cours:psy-l1-s2-ue3-psychologie-de-ladolescent-cm03-le-developpement-cognitif",
    "slug": "cm03-le-developpement-cognitif.md",
    "title": "CM03 — Le développement cognitif",
    "module": "CM — Psychologie de l’adolescent",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 3,
    "description": "Introduction à la relation cognition & psychologie",
    "themes": [
      "Psychologie du développement",
      "Adolescence"
    ],
    "keywords": [
      "CM03 — Le développement cognitif",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/PSYCHOLOGIE DE L ADOLESCENT/CM03 - Le développement cognitif.docx",
      "CM — Psychologie de l’adolescent",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/psychologie-de-ladolescent/cm03-le-developpement-cognitif.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-psychologie-de-ladolescent-cm03-le-developpement-cognitif"
  },
  {
    "id": "cours:psy-l1-s2-ue3-psychologie-de-ladolescent-cm04-le-developpement-moral",
    "slug": "cm04-le-developpement-moral.md",
    "title": "CM04 — Le développement moral",
    "module": "CM — Psychologie de l’adolescent",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 4,
    "description": "La pensée morale est l’ensemble des critères utilisés par une personne pour juger du caractère juste ou injuste, bon ou mauvais des comportements",
    "themes": [
      "Psychologie du développement",
      "Adolescence"
    ],
    "keywords": [
      "CM04 — Le développement moral",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/PSYCHOLOGIE DE L ADOLESCENT/CM04 - Le développement moral.docx",
      "CM — Psychologie de l’adolescent",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/psychologie-de-ladolescent/cm04-le-developpement-moral.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-psychologie-de-ladolescent-cm04-le-developpement-moral"
  },
  {
    "id": "cours:psy-l1-s2-ue3-psychologie-de-ladolescent-cm05-developpement-psychosexuel",
    "slug": "cm05-developpement-psychosexuel.md",
    "title": "CM05 — Développement psychosexuel",
    "module": "CM — Psychologie de l’adolescent",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 5,
    "description": "Réaménagements psychiques et sexualité à l’adolescence",
    "themes": [
      "Psychologie du développement",
      "Adolescence"
    ],
    "keywords": [
      "CM05 — Développement psychosexuel",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/PSYCHOLOGIE DE L ADOLESCENT/CM05 - Développement psychosexuel.docx",
      "CM — Psychologie de l’adolescent",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/psychologie-de-ladolescent/cm05-developpement-psychosexuel.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-psychologie-de-ladolescent-cm05-developpement-psychosexuel"
  },
  {
    "id": "cours:psy-l1-s2-ue3-psychologie-de-ladolescent-cm06-developpement-identitaire",
    "slug": "cm06-developpement-identitaire.md",
    "title": "CM06 — Développement identitaire",
    "module": "CM — Psychologie de l’adolescent",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 6,
    "description": "Le développement identitaire à l’adolescence : quête ou crise identitaire ?",
    "themes": [
      "Psychologie du développement",
      "Adolescence"
    ],
    "keywords": [
      "CM06 — Développement identitaire",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/PSYCHOLOGIE DE L ADOLESCENT/CM06 - Développement identitaire.docx",
      "CM — Psychologie de l’adolescent",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/psychologie-de-ladolescent/cm06-developpement-identitaire.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-psychologie-de-ladolescent-cm06-developpement-identitaire"
  },
  {
    "id": "cours:psy-l1-s2-ue3-psychologie-de-ladolescent-cm07-les-relations-parents-adolescents",
    "slug": "cm07-les-relations-parents-adolescents.md",
    "title": "CM07 — Les relations parents-adolescents",
    "module": "CM — Psychologie de l’adolescent",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 7,
    "description": "L’objectif du cours est de comprendre que dans le processus de séparation-individuation, les parents doivent accepter les conflits déclenchés par l’adolescent et y résister car ils sont une manière pour lui de poser des limites et de tester tout autant les lie…",
    "themes": [
      "Psychologie du développement",
      "Adolescence"
    ],
    "keywords": [
      "CM07 — Les relations parents-adolescents",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/PSYCHOLOGIE DE L ADOLESCENT/CM07 - Les relations parents-adolescents.docx",
      "CM — Psychologie de l’adolescent",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/psychologie-de-ladolescent/cm07-les-relations-parents-adolescents.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-psychologie-de-ladolescent-cm07-les-relations-parents-adolescents"
  },
  {
    "id": "cours:psy-l1-s2-ue3-psychologie-de-ladolescent-cm08-le-developpement-social-a-l-adolescence",
    "slug": "cm08-le-developpement-social-a-l-adolescence.md",
    "title": "CM08 — Le développement social à l adolescence",
    "module": "CM — Psychologie de l’adolescent",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 8,
    "description": "L’objectif du cours est de comprendre le rôle de l’appartenance au groupe dans le processus de socialisation à l’adolescence, de prendre conscience du danger potentiel de la perte de sa personnalité au profit d’un idéal du moi collectif ainsi que de distinguer…",
    "themes": [
      "Psychologie du développement",
      "Adolescence"
    ],
    "keywords": [
      "CM08 — Le développement social à l adolescence",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/PSYCHOLOGIE DE L ADOLESCENT/CM08 - Le développement social à l adolescence.docx",
      "CM — Psychologie de l’adolescent",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/psychologie-de-ladolescent/cm08-le-developpement-social-a-l-adolescence.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-psychologie-de-ladolescent-cm08-le-developpement-social-a-l-adolescence"
  },
  {
    "id": "cours:psy-l1-s2-ue3-psychologie-de-ladolescent-cm09-de-la-transgression-des-regles-aux-conduites-a-risques",
    "slug": "cm09-de-la-transgression-des-regles-aux-conduites-a-risques.md",
    "title": "CM09 — De la transgression des règles aux conduites à risques",
    "module": "CM — Psychologie de l’adolescent",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 9,
    "description": "De la transgression des règles aux conduites à risques",
    "themes": [
      "Psychologie du développement",
      "Adolescence"
    ],
    "keywords": [
      "CM09 — De la transgression des règles aux conduites à risques",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/PSYCHOLOGIE DE L ADOLESCENT/CM09 - De la transgression des règles aux conduites à risques.docx",
      "CM — Psychologie de l’adolescent",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/psychologie-de-ladolescent/cm09-de-la-transgression-des-regles-aux-conduites-a-risques.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-psychologie-de-ladolescent-cm09-de-la-transgression-des-regles-aux-conduites-a-risques"
  },
  {
    "id": "cours:psy-l1-s2-ue3-psychologie-de-ladolescent-cm10-attentes-personnelles-et-intentions-proessionnelles-motivation-violence-decrochage",
    "slug": "cm10-attentes-personnelles-et-intentions-proessionnelles-motivation-violence-decrochage.md",
    "title": "CM10 — Attentes personnelles et intentions proessionnelles, motivation, violence, décrochage",
    "module": "CM — Psychologie de l’adolescent",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 10,
    "description": "Attentes personnelles et intentions professionnelles, motivation, violence, décrochage",
    "themes": [
      "Psychologie du développement",
      "Adolescence",
      "Violence"
    ],
    "keywords": [
      "CM10 — Attentes personnelles et intentions proessionnelles, motivation, violence, décrochage",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/PSYCHOLOGIE DE L ADOLESCENT/CM10 - Attentes personnelles et intentions proessionnelles, motivation, violence, décrochage.docx",
      "CM — Psychologie de l’adolescent",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Psychologie de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/psychologie-de-ladolescent/cm10-attentes-personnelles-et-intentions-proessionnelles-motivation-violence-decrochage.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-psychologie-de-ladolescent-cm10-attentes-personnelles-et-intentions-proessionnelles-motivation-violence-decrochage"
  },
  {
    "id": "cours:psy-l1-s2-ue3-questions-actuelles-cm01-02-quelles-sont-les-competences-des-jeunes-bebes",
    "slug": "cm01-02-quelles-sont-les-competences-des-jeunes-bebes.md",
    "title": "CM01-02- Quelles sont les compétences des jeunes bébés",
    "module": "CM — Questions actuelles",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 1,
    "description": "Quelles sont les compétences des jeunes bébés ?",
    "themes": [
      "Psychologie",
      "Questions actuelles"
    ],
    "keywords": [
      "CM01-02- Quelles sont les compétences des jeunes bébés",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/QUESTIONS ACTUELLES/CM01-02- Quelles sont les compétences des jeunes bébés.docx",
      "CM — Questions actuelles",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Questions actuelles",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/questions-actuelles/cm01-02-quelles-sont-les-competences-des-jeunes-bebes.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-questions-actuelles-cm01-02-quelles-sont-les-competences-des-jeunes-bebes"
  },
  {
    "id": "cours:psy-l1-s2-ue3-questions-actuelles-cm03-la-couleur",
    "slug": "cm03-la-couleur.md",
    "title": "CM03 — La couleur",
    "module": "CM — Questions actuelles",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 2,
    "description": "Parmi la population, il 10% de daltonien (manque de photorécepteurs). Est-ce qu’une couleur est la même pour tout le monde ?",
    "themes": [
      "Psychologie",
      "Questions actuelles",
      "Perception"
    ],
    "keywords": [
      "CM03 — La couleur",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/QUESTIONS ACTUELLES/CM03 - La couleur.docx",
      "CM — Questions actuelles",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Questions actuelles",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/questions-actuelles/cm03-la-couleur.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-questions-actuelles-cm03-la-couleur"
  },
  {
    "id": "cours:psy-l1-s2-ue3-questions-actuelles-cm05-06-illusions-visuelles",
    "slug": "cm05-06-illusions-visuelles.md",
    "title": "CM05-06 — Illusions visuelles",
    "module": "CM — Questions actuelles",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 3,
    "description": "Une illusion visuelle est-elle une erreur perceptive ?",
    "themes": [
      "Psychologie",
      "Questions actuelles"
    ],
    "keywords": [
      "CM05-06 — Illusions visuelles",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/QUESTIONS ACTUELLES/CM05-06 - Illusions visuelles.docx",
      "CM — Questions actuelles",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Questions actuelles",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/questions-actuelles/cm05-06-illusions-visuelles.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-questions-actuelles-cm05-06-illusions-visuelles"
  },
  {
    "id": "cours:psy-l1-s2-ue3-questions-actuelles-cm06-07-les-faux-souvenirs",
    "slug": "cm06-07-les-faux-souvenirs.md",
    "title": "CM06-07 — Les faux souvenirs",
    "module": "CM — Questions actuelles",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 4,
    "description": "Sur 300 personnes condamnées, ¾ des condamnations sont sur des bases de témoignages visuels. Les personnes vont être sincère (ce n’est pas du mensonge). Un faux souvenir est sincère et va évoquer des souvenirs qui ne sont pas juste (/réel)",
    "themes": [
      "Psychologie",
      "Questions actuelles",
      "Mémoire"
    ],
    "keywords": [
      "CM06-07 — Les faux souvenirs",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/QUESTIONS ACTUELLES/CM06-07 - Les faux souvenirs.docx",
      "CM — Questions actuelles",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Questions actuelles",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/questions-actuelles/cm06-07-les-faux-souvenirs.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-questions-actuelles-cm06-07-les-faux-souvenirs"
  },
  {
    "id": "cours:psy-l1-s2-ue3-questions-actuelles-cm08-09-les-femmes-viennent-de-venus-les-hommes-de-mars",
    "slug": "cm08-09-les-femmes-viennent-de-venus-les-hommes-de-mars.md",
    "title": "CM08-09 — Les femmes viennent de Venus, les hommes de Mars",
    "module": "CM — Questions actuelles",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 5,
    "description": "Les femmes viennent de Venus, les hommes de Mars",
    "themes": [
      "Psychologie",
      "Questions actuelles"
    ],
    "keywords": [
      "CM08-09 — Les femmes viennent de Venus, les hommes de Mars",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/QUESTIONS ACTUELLES/CM08-09 - Les femmes viennent de Venus, les hommes de Mars.docx",
      "CM — Questions actuelles",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Questions actuelles",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/questions-actuelles/cm08-09-les-femmes-viennent-de-venus-les-hommes-de-mars.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-questions-actuelles-cm08-09-les-femmes-viennent-de-venus-les-hommes-de-mars"
  },
  {
    "id": "cours:psy-l1-s2-ue3-questions-actuelles-cm10-le-deja-vu",
    "slug": "cm10-le-deja-vu.md",
    "title": "CM10 — Le déjà-vu",
    "module": "CM — Questions actuelles",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 6,
    "description": "C’est une expérience pas très fréquente. Cela arrive avec les personnes fatigué, prend les drogues, intelligent, intelligent…",
    "themes": [
      "Psychologie",
      "Questions actuelles"
    ],
    "keywords": [
      "CM10 — Le déjà-vu",
      "UE3 - PSYCHO DE L ADO & QUESTIONS ACTUELLES/QUESTIONS ACTUELLES/CM10 - Le déjà-vu.docx",
      "CM — Questions actuelles",
      "UE3 — Psychologie de l’adolescent & questions actuelles",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE3 — Psychologie de l’adolescent & questions actuelles",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Questions actuelles",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue3/questions-actuelles/cm10-le-deja-vu.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue3-questions-actuelles-cm10-le-deja-vu"
  },
  {
    "id": "cours:psy-l1-s2-ue4-sociologie-de-la-culture-cm01-sociologie-de-la-culture",
    "slug": "cm01-sociologie-de-la-culture.md",
    "title": "CM01 — Sociologie de la culture",
    "module": "CM — Sociologie de la culture",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 1,
    "description": "La notion de culture est inhérente à la réflexion des sciences sociales. C’est l’une des réponses satisfaisante pour répondre à la question des différences entre les sociétés / personnes. La réponse raciale est discréditée. La question de race apparait réguliè…",
    "themes": [
      "Sociologie",
      "Culture"
    ],
    "keywords": [
      "CM01 — Sociologie de la culture",
      "UE4 - SOCIOLOGIE/SOCIOLOGIE DE LA CULTURE/CM01 - Sociologie de la culture.docx",
      "CM — Sociologie de la culture",
      "UE4 — Sociologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE4 — Sociologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Sociologie de la culture",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue4/sociologie-de-la-culture/cm01-sociologie-de-la-culture.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue4-sociologie-de-la-culture-cm01-sociologie-de-la-culture"
  },
  {
    "id": "cours:psy-l1-s2-ue4-sociologie-de-la-culture-cm02-le-courant-evolutionniste",
    "slug": "cm02-le-courant-evolutionniste.md",
    "title": "CM02 — Le courant évolutionniste",
    "module": "CM — Sociologie de la culture",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 2,
    "description": "On ne peut pas parler de race car il y a trop de différences entre les individus (biologiquement parlant). On va plutôt parler d’espèce humaine (ensemble des organismes qui sont capables de se reproduire)",
    "themes": [
      "Sociologie"
    ],
    "keywords": [
      "CM02 — Le courant évolutionniste",
      "UE4 - SOCIOLOGIE/SOCIOLOGIE DE LA CULTURE/CM02 - Le courant évolutionniste.docx",
      "CM — Sociologie de la culture",
      "UE4 — Sociologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE4 — Sociologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Sociologie de la culture",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue4/sociologie-de-la-culture/cm02-le-courant-evolutionniste.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue4-sociologie-de-la-culture-cm02-le-courant-evolutionniste"
  },
  {
    "id": "cours:psy-l1-s2-ue4-sociologie-de-la-culture-cm03-diffusionnisme-fonctionnalisme",
    "slug": "cm03-diffusionnisme-fonctionnalisme.md",
    "title": "CM03 — Diffusionnisme & fonctionnalisme",
    "module": "CM — Sociologie de la culture",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 3,
    "description": "L’évolutionnisme est très déconstruit. Les théories sont plus ou moins convaincantes. Certaines sociétés vont être placés supérieur à d’autres. On va avoir des courants de pensées différents dont un courant qui a réagi à l’évolutionnisme qui est le diffusionni…",
    "themes": [
      "Sociologie"
    ],
    "keywords": [
      "CM03 — Diffusionnisme & fonctionnalisme",
      "UE4 - SOCIOLOGIE/SOCIOLOGIE DE LA CULTURE/CM03 - Diffusionnisme & fonctionnalisme.docx",
      "CM — Sociologie de la culture",
      "UE4 — Sociologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE4 — Sociologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Sociologie de la culture",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue4/sociologie-de-la-culture/cm03-diffusionnisme-fonctionnalisme.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue4-sociologie-de-la-culture-cm03-diffusionnisme-fonctionnalisme"
  },
  {
    "id": "cours:psy-l1-s2-ue4-sociologie-de-la-culture-cm04-l-acculturation",
    "slug": "cm04-l-acculturation.md",
    "title": "CM04 — L acculturation",
    "module": "CM — Sociologie de la culture",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 4,
    "description": "M.Mauss dit que le don n’est pas un acte altruiste et est disponible pour toutes les sociétés. Ce n’est pas un acte de générosité. Pour l’anthropologue, le don est articulé avec un contre don avec une triple obligation : donner, recevoir, rendre. On se trouve…",
    "themes": [
      "Sociologie"
    ],
    "keywords": [
      "CM04 — L acculturation",
      "UE4 - SOCIOLOGIE/SOCIOLOGIE DE LA CULTURE/CM04 - L acculturation.docx",
      "CM — Sociologie de la culture",
      "UE4 — Sociologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE4 — Sociologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Sociologie de la culture",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue4/sociologie-de-la-culture/cm04-l-acculturation.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue4-sociologie-de-la-culture-cm04-l-acculturation"
  },
  {
    "id": "cours:psy-l1-s2-ue4-sociologie-de-la-culture-cm05-06-le-concept-d-acculturation",
    "slug": "cm05-06-le-concept-d-acculturation.md",
    "title": "CM05-06 — Le concept d acculturation",
    "module": "CM — Sociologie de la culture",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 5,
    "description": "Les diffusionnistes vont parler de contact culturel (des sociétés soumis à des lois universelles). On a une présentation d’un modèle linéaire, les diffusionnistes sont les premiers qui s’intéresse à la diffusion de traits culturels (= forme familial, méthode d…",
    "themes": [
      "Sociologie"
    ],
    "keywords": [
      "CM05-06 — Le concept d acculturation",
      "UE4 - SOCIOLOGIE/SOCIOLOGIE DE LA CULTURE/CM05-06 - Le concept d acculturation.docx",
      "CM — Sociologie de la culture",
      "UE4 — Sociologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE4 — Sociologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Sociologie de la culture",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue4/sociologie-de-la-culture/cm05-06-le-concept-d-acculturation.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue4-sociologie-de-la-culture-cm05-06-le-concept-d-acculturation"
  },
  {
    "id": "cours:psy-l1-s2-ue4-sociologie-de-la-culture-cm06-08-la-culture-comme-capital",
    "slug": "cm06-08-la-culture-comme-capital.md",
    "title": "CM06-08 — La culture comme capital",
    "module": "CM — Sociologie de la culture",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 6,
    "description": "La culture s’oppose à la nature. On étudie en anthropologie ce qui est le propre de l’Homme. Les singes ne seraient pas nos ancêtres mais nos cousins. Le rire serait le propre de l’Homme (car les animaux ne comprennent pas qu’il y a un premier / second degré)…",
    "themes": [
      "Sociologie",
      "Culture"
    ],
    "keywords": [
      "CM06-08 — La culture comme capital",
      "UE4 - SOCIOLOGIE/SOCIOLOGIE DE LA CULTURE/CM06-08 - La culture comme capital.docx",
      "CM — Sociologie de la culture",
      "UE4 — Sociologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE4 — Sociologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Sociologie de la culture",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue4/sociologie-de-la-culture/cm06-08-la-culture-comme-capital.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue4-sociologie-de-la-culture-cm06-08-la-culture-comme-capital"
  },
  {
    "id": "cours:psy-l1-s2-ue4-sociologie-du-travail-cm01-sociologie-du-travail",
    "slug": "cm01-sociologie-du-travail.md",
    "title": "CM01 — Sociologie du travail",
    "module": "CM — Sociologie du travail",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 1,
    "description": "Les étudiant ne seraient pas des travailleurs intellectuels en formation ou des inactifs ? Un stagiaire c’est quoi ? J’ai un parent à charge chez moi et alors ? Le premier facteur d’échec à la FAC est le travail à côté (salarié)",
    "themes": [
      "Sociologie",
      "Travail"
    ],
    "keywords": [
      "CM01 — Sociologie du travail",
      "UE4 - SOCIOLOGIE/SOCIOLOGIE DU TRAVAIL/CM01 - Sociologie du travail.docx",
      "CM — Sociologie du travail",
      "UE4 — Sociologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE4 — Sociologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Sociologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue4/sociologie-du-travail/cm01-sociologie-du-travail.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue4-sociologie-du-travail-cm01-sociologie-du-travail"
  },
  {
    "id": "cours:psy-l1-s2-ue4-sociologie-du-travail-cm02-03-l-epanouissement-avec-le-travail",
    "slug": "cm02-03-l-epanouissement-avec-le-travail.md",
    "title": "CM02-03 — L épanouissement avec le travail",
    "module": "CM — Sociologie du travail",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 2,
    "description": "Au XIX°, le travail acquiert une autre valeur : celle d’épanouissement personnel. On va le définir comme un moyen de réalisation de soi. Tout se passe comme si le travail est la nature de la personne et donc qu’en travaillant, il est lui-même. D.Méda à travail…",
    "themes": [
      "Sociologie",
      "Travail"
    ],
    "keywords": [
      "CM02-03 — L épanouissement avec le travail",
      "UE4 - SOCIOLOGIE/SOCIOLOGIE DU TRAVAIL/CM02-03 - L épanouissement avec le travail.docx",
      "CM — Sociologie du travail",
      "UE4 — Sociologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE4 — Sociologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Sociologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue4/sociologie-du-travail/cm02-03-l-epanouissement-avec-le-travail.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue4-sociologie-du-travail-cm02-03-l-epanouissement-avec-le-travail"
  },
  {
    "id": "cours:psy-l1-s2-ue4-sociologie-du-travail-cm04-la-femme-dans-notre-societe",
    "slug": "cm04-la-femme-dans-notre-societe.md",
    "title": "CM04 — La femme dans notre société",
    "module": "CM — Sociologie du travail",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 3,
    "description": "On va avoir 80% de main d’œuvre dans les secteurs tertiaire. Les secteurs touchés sont soit le secteur agricole soir le secteur industrielle",
    "themes": [
      "Sociologie"
    ],
    "keywords": [
      "CM04 — La femme dans notre société",
      "UE4 - SOCIOLOGIE/SOCIOLOGIE DU TRAVAIL/CM04 - La femme dans notre société.docx",
      "CM — Sociologie du travail",
      "UE4 — Sociologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE4 — Sociologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Sociologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue4/sociologie-du-travail/cm04-la-femme-dans-notre-societe.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue4-sociologie-du-travail-cm04-la-femme-dans-notre-societe"
  },
  {
    "id": "cours:psy-l1-s2-ue4-sociologie-du-travail-cm05-la-banale-journee-d-un-marin",
    "slug": "cm05-la-banale-journee-d-un-marin.md",
    "title": "CM05 — La banale journée d un marin",
    "module": "CM — Sociologie du travail",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 4,
    "description": "Référence au texte : la banale journée d’un marin",
    "themes": [
      "Sociologie"
    ],
    "keywords": [
      "CM05 — La banale journée d un marin",
      "UE4 - SOCIOLOGIE/SOCIOLOGIE DU TRAVAIL/CM05 - La banale journée d un marin.docx",
      "CM — Sociologie du travail",
      "UE4 — Sociologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE4 — Sociologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Sociologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue4/sociologie-du-travail/cm05-la-banale-journee-d-un-marin.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue4-sociologie-du-travail-cm05-la-banale-journee-d-un-marin"
  },
  {
    "id": "cours:psy-l1-s2-ue5-anglais-cm02-article-pronunciation",
    "slug": "cm02-article-pronunciation.md",
    "title": "CM02 Article — Pronunciation",
    "module": "CM — Anglais",
    "courseTheme": "methodologie",
    "sourceType": "Support de CM",
    "format": "Article / notes de cours",
    "sequence": 1,
    "description": "Brummie accents 'worse than staying silent', study shows",
    "themes": [
      "Anglais",
      "Méthodologie"
    ],
    "keywords": [
      "CM02 Article — Pronunciation",
      "UE5 - METHODOLOGIE/ANGLAIS/CM02 Article - Pronunciation.docx",
      "CM — Anglais",
      "UE5 — Méthodologie",
      "Support de CM"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE5 — Méthodologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Anglais",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue5/anglais/cm02-article-pronunciation.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue5-anglais-cm02-article-pronunciation"
  },
  {
    "id": "cours:psy-l1-s2-ue5-traitement-des-donnees-cm01-02-theorie-et-description",
    "slug": "cm01-02-theorie-et-description.md",
    "title": "CM01-02 — Théorie et description",
    "module": "CM — Traitement des données",
    "courseTheme": "methodologie",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours / statistiques",
    "sequence": 1,
    "description": "On a un besoin de compréhension et de simplification. Les choses peuvent être dut aux hasards, peuvent être indéterminé, chaotique … S’il y a trop de facteurs, la solution serait compliquées à trouver (trop de paramètre). Le monde réel est complexe (surtout l’…",
    "themes": [
      "Méthodologie",
      "Statistiques"
    ],
    "keywords": [
      "CM01-02 — Théorie et description",
      "UE5 - METHODOLOGIE/TRAITEMENT DES DONNEES/CM01-02 - Théorie et description.docx",
      "CM — Traitement des données",
      "UE5 — Méthodologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE5 — Méthodologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Traitement des données",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue5/traitement-des-donnees/cm01-02-theorie-et-description.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue5-traitement-des-donnees-cm01-02-theorie-et-description"
  },
  {
    "id": "cours:psy-l1-s2-ue5-traitement-des-donnees-cm01-introduction-traitement-des-donnees",
    "slug": "cm01-introduction-traitement-des-donnees.md",
    "title": "CM01 — Introduction traitement des données",
    "module": "CM — Traitement des données",
    "courseTheme": "methodologie",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours / statistiques",
    "sequence": 2,
    "description": "Les faux positifs sont importants et à prendre en compte car ils peuvent influencer soi, l’autre et avoir de grave impact. Le fait d’avoir une connaissance de celle-là, on pourra voir défauts ou simplification des études. Les statistiques permettent de général…",
    "themes": [
      "Méthodologie",
      "Statistiques"
    ],
    "keywords": [
      "CM01 — Introduction traitement des données",
      "UE5 - METHODOLOGIE/TRAITEMENT DES DONNEES/CM01 - Introduction traitement des données.docx",
      "CM — Traitement des données",
      "UE5 — Méthodologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE5 — Méthodologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Traitement des données",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue5/traitement-des-donnees/cm01-introduction-traitement-des-donnees.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue5-traitement-des-donnees-cm01-introduction-traitement-des-donnees"
  },
  {
    "id": "cours:psy-l1-s2-ue5-traitement-des-donnees-cm02-03-distribution-d-une-variable",
    "slug": "cm02-03-distribution-d-une-variable.md",
    "title": "CM02-03 — Distribution d une variable",
    "module": "CM — Traitement des données",
    "courseTheme": "methodologie",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours / statistiques",
    "sequence": 3,
    "description": "On va avoir plusieurs options pour parler des données : des données brutes (matrices, très complexe, on ne peut pas voir toutes les choses directement avec cela). Il va donc falloir distribuer les informations et simplifié les choses en résumant les chiffres /…",
    "themes": [
      "Méthodologie",
      "Statistiques"
    ],
    "keywords": [
      "CM02-03 — Distribution d une variable",
      "UE5 - METHODOLOGIE/TRAITEMENT DES DONNEES/CM02-03 - Distribution d une variable.docx",
      "CM — Traitement des données",
      "UE5 — Méthodologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE5 — Méthodologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Traitement des données",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue5/traitement-des-donnees/cm02-03-distribution-d-une-variable.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue5-traitement-des-donnees-cm02-03-distribution-d-une-variable"
  },
  {
    "id": "cours:psy-l1-s2-ue5-traitement-des-donnees-cm03-04-resumes-d-une-variable",
    "slug": "cm03-04-resumes-d-une-variable.md",
    "title": "CM03-04- Résumés d une variable",
    "module": "CM — Traitement des données",
    "courseTheme": "methodologie",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours / statistiques",
    "sequence": 4,
    "description": "Pour résumé un ensemble (une situation), on va utiliser des indices statistiques. Ainsi on va avoir plusieurs options qui dépendent du niveau d’échelle (qualitative, quantitative) et on se demander de faire un résumé de quoi ?",
    "themes": [
      "Méthodologie",
      "Statistiques"
    ],
    "keywords": [
      "CM03-04- Résumés d une variable",
      "UE5 - METHODOLOGIE/TRAITEMENT DES DONNEES/CM03-04- Résumés d une variable.docx",
      "CM — Traitement des données",
      "UE5 — Méthodologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE5 — Méthodologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Traitement des données",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue5/traitement-des-donnees/cm03-04-resumes-d-une-variable.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue5-traitement-des-donnees-cm03-04-resumes-d-une-variable"
  },
  {
    "id": "cours:psy-l1-s2-ue5-traitement-des-donnees-cm05a-distribution-de-deux-variables",
    "slug": "cm05a-distribution-de-deux-variables.md",
    "title": "CM05A — Distribution de deux variables",
    "module": "CM — Traitement des données",
    "courseTheme": "methodologie",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours / statistiques",
    "sequence": 5,
    "description": "Pourquoi a-t-on besoin d’étudier deux variables ?",
    "themes": [
      "Méthodologie",
      "Statistiques"
    ],
    "keywords": [
      "CM05A — Distribution de deux variables",
      "UE5 - METHODOLOGIE/TRAITEMENT DES DONNEES/CM05A - Distribution de deux variables.docx",
      "CM — Traitement des données",
      "UE5 — Méthodologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE5 — Méthodologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Traitement des données",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue5/traitement-des-donnees/cm05a-distribution-de-deux-variables.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue5-traitement-des-donnees-cm05a-distribution-de-deux-variables"
  },
  {
    "id": "cours:psy-l1-s2-ue5-traitement-des-donnees-cm05b-indicide-de-liaison-et-d-association",
    "slug": "cm05b-indicide-de-liaison-et-d-association.md",
    "title": "CM05B — Indicide de liaison et d association",
    "module": "CM — Traitement des données",
    "courseTheme": "methodologie",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours / statistiques",
    "sequence": 6,
    "description": "Quand il y a deux variables, il y a eu deux tendances :",
    "themes": [
      "Méthodologie",
      "Statistiques"
    ],
    "keywords": [
      "CM05B — Indicide de liaison et d association",
      "UE5 - METHODOLOGIE/TRAITEMENT DES DONNEES/CM05B - Indicide de liaison et d association.docx",
      "CM — Traitement des données",
      "UE5 — Méthodologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE5 — Méthodologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Traitement des données",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue5/traitement-des-donnees/cm05b-indicide-de-liaison-et-d-association.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue5-traitement-des-donnees-cm05b-indicide-de-liaison-et-d-association"
  },
  {
    "id": "cours:psy-l1-s2-ue6-zetetique-defense-intellectuelle-cm0103-zetetique-classique-epistemologie",
    "slug": "cm0103-zetetique-classique-epistemologie.md",
    "title": "CM01–03 — Zététique classique & épistémologie",
    "module": "CM — Zététique & défense intellectuelle",
    "courseTheme": "methodologie",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 1,
    "description": "Le cours de zététique sera divisé en 4 leçons & 12 CM :",
    "themes": [
      "Zététique",
      "Esprit critique",
      "Épistémologie"
    ],
    "keywords": [
      "CM01–03 — Zététique classique & épistémologie",
      "UE6 - ZETETIQUE & DEFENSE INTELLECTUEL/CM01 03 - Zététique classique & épistémologie.docx",
      "CM — Zététique & défense intellectuelle",
      "UE6 — Zététique & défense intellectuelle",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE6 — Zététique & défense intellectuelle",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Zététique & défense intellectuelle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue6/zetetique-defense-intellectuelle/cm0103-zetetique-classique-epistemologie.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue6-zetetique-defense-intellectuelle-cm0103-zetetique-classique-epistemologie"
  },
  {
    "id": "cours:psy-l1-s2-ue6-zetetique-defense-intellectuelle-cm02-propagande-de-guerre",
    "slug": "cm02-propagande-de-guerre.md",
    "title": "CM02 — Propagande de guerre",
    "module": "CM — Zététique & défense intellectuelle",
    "courseTheme": "methodologie",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 2,
    "description": "Les interventions militaires / la guerre n’est pas très populaire. Pourtant elle n’a pas disparu. Les interventions récentes sont pourtant efficaces",
    "themes": [
      "Zététique",
      "Esprit critique",
      "Épistémologie",
      "Propagande"
    ],
    "keywords": [
      "CM02 — Propagande de guerre",
      "UE6 - ZETETIQUE & DEFENSE INTELLECTUEL/CM02 - Propagande de guerre.docx",
      "CM — Zététique & défense intellectuelle",
      "UE6 — Zététique & défense intellectuelle",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE6 — Zététique & défense intellectuelle",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Zététique & défense intellectuelle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue6/zetetique-defense-intellectuelle/cm02-propagande-de-guerre.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue6-zetetique-defense-intellectuelle-cm02-propagande-de-guerre"
  },
  {
    "id": "cours:psy-l1-s2-ue6-zetetique-defense-intellectuelle-cm04-outils-epistemologiques-comment-soupeser-des-hypotheses",
    "slug": "cm04-outils-epistemologiques-comment-soupeser-des-hypotheses.md",
    "title": "CM04 — Outils épistémologiques — Comment soupeser des hypothèses",
    "module": "CM — Zététique & défense intellectuelle",
    "courseTheme": "methodologie",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 3,
    "description": "Cours dédier au président du Maharashtra Andhashraddha Nirmoolan Samati (MANS), comité pour éradiquer la superstition dans Marashtra, militait pour l’ordonnance « Anti-superstition and black magic », assassiné le 20/07/13)",
    "themes": [
      "Zététique",
      "Esprit critique",
      "Épistémologie"
    ],
    "keywords": [
      "CM04 — Outils épistémologiques — Comment soupeser des hypothèses",
      "UE6 - ZETETIQUE & DEFENSE INTELLECTUEL/CM04 - Outils épistémologiques - Comment soupeser des hypothèses.docx",
      "CM — Zététique & défense intellectuelle",
      "UE6 — Zététique & défense intellectuelle",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE6 — Zététique & défense intellectuelle",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Zététique & défense intellectuelle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue6/zetetique-defense-intellectuelle/cm04-outils-epistemologiques-comment-soupeser-des-hypotheses.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue6-zetetique-defense-intellectuelle-cm04-outils-epistemologiques-comment-soupeser-des-hypotheses"
  },
  {
    "id": "cours:psy-l1-s2-ue6-zetetique-defense-intellectuelle-cm05-medecines-alternatives-elements-de-critique",
    "slug": "cm05-medecines-alternatives-elements-de-critique.md",
    "title": "CM05 — Médecines alternatives — Éléments de critique",
    "module": "CM — Zététique & défense intellectuelle",
    "courseTheme": "methodologie",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 4,
    "description": "Notre pensée va comparer des choses que l’on voit a d’autre chose qu’on connait",
    "themes": [
      "Zététique",
      "Esprit critique",
      "Épistémologie"
    ],
    "keywords": [
      "CM05 — Médecines alternatives — Éléments de critique",
      "UE6 - ZETETIQUE & DEFENSE INTELLECTUEL/CM05 - Médecines  alternatives  - Éléments de critique.docx",
      "CM — Zététique & défense intellectuelle",
      "UE6 — Zététique & défense intellectuelle",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 2",
    "ue": "UE6 — Zététique & défense intellectuelle",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S2",
    "subject": "CM — Zététique & défense intellectuelle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s2/ue6/zetetique-defense-intellectuelle/cm05-medecines-alternatives-elements-de-critique.md",
    "url": "/mediatheque/cours/?id=psy-l1-s2-ue6-zetetique-defense-intellectuelle-cm05-medecines-alternatives-elements-de-critique"
  }
];
  const norm = (v="") => String(v).replace(/\/+$/, "");
  const ids = new Set(DATA.resources.map(x => x && x.id).filter(Boolean));
  const urls = new Set(DATA.resources.map(x => norm(x && x.contentUrl || "")).filter(Boolean));
  let added = 0;
  incoming.forEach(item => {
    if (!item || ids.has(item.id) || urls.has(norm(item.contentUrl))) return;
    DATA.resources.push(item); ids.add(item.id); urls.add(norm(item.contentUrl)); added += 1;
  });
  window.FV_S2_COURSES_STATUS = { ok: true, added, supplied: incoming.length };

  // Merge the S2 full-text index on top of the existing index (and the S1 patch if installed).
  if (!window.__FV_S2_FETCH_PATCHED) {
    window.__FV_S2_FETCH_PATCHED = true;
    const nativeFetch = window.fetch.bind(window);
    const scriptUrl = (document.currentScript && document.currentScript.src) || location.href;
    const extraIndexUrl = new URL('./cours/s2-search-index.json', scriptUrl).href;
    window.fetch = async function(input, init) {
      let url = '';
      try { url = typeof input === 'string' ? new URL(input, location.href).href : new URL(input.url, location.href).href; } catch (_) {}
      if (!/\/mediatheque\/cours\/search-index\.json(?:[?#]|$)/.test(url)) return nativeFetch(input, init);
      const [baseResponse, extraResponse] = await Promise.all([
        nativeFetch(input, init).catch(() => null),
        nativeFetch(extraIndexUrl, { cache:'no-store', credentials:'same-origin' }).catch(() => null)
      ]);
      let base={}, extra={};
      try { if (baseResponse && baseResponse.ok) base=await baseResponse.clone().json(); } catch (_) {}
      try { if (extraResponse && extraResponse.ok) extra=await extraResponse.json(); } catch (_) {}
      return new Response(JSON.stringify({ ...base, ...extra }), { status:200, headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'} });
    };
  }

  function sitePrefix() {
    const p=location.pathname.replace(/\/index\.html$/i,'/'); const marker='/mediatheque/'; const i=p.indexOf(marker); return i>0?p.slice(0,i):'';
  }
  function imageUrl(v) { v=String(v||'').trim(); return v.startsWith('/') ? (sitePrefix()+v || v) : v; }
  function hydrateImages(root=document) {
    root.querySelectorAll && root.querySelectorAll('.course-content p').forEach(p => {
      const txt=(p.textContent||'').trim(); const m=txt.match(/^\[\[image:([^|]+)\|([^\]]*)\]\]$/); if(!m) return;
      const fig=document.createElement('figure'); fig.className='course-embedded-image'; fig.style.cssText='margin:1.55rem 0;text-align:center';
      const img=document.createElement('img'); img.src=imageUrl(m[1]); img.alt=m[2]||'Illustration du cours'; img.loading='lazy'; img.style.cssText='display:block;max-width:100%;height:auto;margin:0 auto;border-radius:6px';
      fig.appendChild(img); p.replaceWith(fig);
    });
  }
  function observeImages() { const target=document.querySelector('[data-course-content]'); if(!target) return; hydrateImages(document); new MutationObserver(()=>hydrateImages(document)).observe(target,{childList:true,subtree:true}); }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',observeImages,{once:true}); else observeImages();
})();
