(() => {
  "use strict";
  const DATA = window.FV_MEDIATHEQUE_DATA || (window.FV_MEDIATHEQUE_DATA = { resources: [], dossiers: [] });
  if (!Array.isArray(DATA.resources)) DATA.resources = [];
  const incoming = [
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-adulte-cm01-02-introduction-a-la-psychopathologie-de-l-adulte",
    "slug": "cm01-02-introduction-a-la-psychopathologie-de-l-adulte.md",
    "title": "CM01-02 — Introduction à la psychopathologie de l adulte",
    "module": "CM — Introduction à la psychopathologie de l’adulte",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 1,
    "description": "Introduction à la psychopathologie adulte Introduction Le mot psychopathologie vient de trois éléments : - Psyché = âme/esprit - Logos = langage, mot, discours - Pathos = la souffrance, maladie, passion C’est l’étude du trouble psychique tel qu’il apparait. El…",
    "themes": [
      "Psychopathologie",
      "Adulte"
    ],
    "keywords": [
      "CM01-02 — Introduction à la psychopathologie de l adulte",
      "UE1 - Psychologie clinique/Introduction à la psychopathologie de l_adulte/CM01-02 - Introduction à la psychopathologie de l_adulte.docx",
      "CM — Introduction à la psychopathologie de l’adulte",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Introduction à la psychopathologie de l’adulte",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-adulte/cm01-02-introduction-a-la-psychopathologie-de-l-adulte.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-adulte-cm01-02-introduction-a-la-psychopathologie-de-l-adulte"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-adulte-cm02-05-l-approche-psychanalytique",
    "slug": "cm02-05-l-approche-psychanalytique.md",
    "title": "CM02-05 — L approche psychanalytique",
    "module": "CM — Introduction à la psychopathologie de l’adulte",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 2,
    "description": "L’approche psychanalytique Freud et la naissance de la psychanalyse CHARCOT est celui qui a apporté une théorie sur l’hystérie. C’était le professeur de FREUD. CHARCOT (et son époque) va essayer de trouver la liaison organique qui peut expliquer la pathologie…",
    "themes": [
      "Psychopathologie",
      "Adulte"
    ],
    "keywords": [
      "CM02-05 — L approche psychanalytique",
      "UE1 - Psychologie clinique/Introduction à la psychopathologie de l_adulte/CM02-05 - L_approche psychanalytique.docx",
      "CM — Introduction à la psychopathologie de l’adulte",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Introduction à la psychopathologie de l’adulte",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-adulte/cm02-05-l-approche-psychanalytique.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-adulte-cm02-05-l-approche-psychanalytique"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-adulte-cm04-05-nevrose-psychoses-et-etats-limites",
    "slug": "cm04-05-nevrose-psychoses-et-etats-limites.md",
    "title": "CM04-05 — Névrose, psychoses et états limites",
    "module": "CM — Introduction à la psychopathologie de l’adulte",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 3,
    "description": "Névroses, psychoses et états limites Névroses introduction Le terme névrose est créé par Williams Cullen à la fin du XVIII°. Elle renvoie à la notion de nerveux. Le terme de névrose et de structure névrotique ne signifie pas la même chose. C’est la description…",
    "themes": [
      "Psychopathologie",
      "Adulte"
    ],
    "keywords": [
      "CM04-05 — Névrose, psychoses et états limites",
      "UE1 - Psychologie clinique/Introduction à la psychopathologie de l_adulte/CM04-05 - Névrose, psychoses et états limites.docx",
      "CM — Introduction à la psychopathologie de l’adulte",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Introduction à la psychopathologie de l’adulte",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-adulte/cm04-05-nevrose-psychoses-et-etats-limites.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-adulte-cm04-05-nevrose-psychoses-et-etats-limites"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-adulte-cm05-06-dsm",
    "slug": "cm05-06-dsm.md",
    "title": "CM05-06 — DSM",
    "module": "CM — Introduction à la psychopathologie de l’adulte",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 4,
    "description": "Approche A-théorique le DSM Le DSM va avoir plusieurs objectifs d’une classification : - Donner une nomenclature aux professionnels - Servir de base pour organiser et retrouver des informations - Décrire uns schéma commun des descriptions des symptômes - Fourn…",
    "themes": [
      "Psychopathologie",
      "Adulte"
    ],
    "keywords": [
      "CM05-06 — DSM",
      "UE1 - Psychologie clinique/Introduction à la psychopathologie de l_adulte/CM05-06 - DSM.docx",
      "CM — Introduction à la psychopathologie de l’adulte",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Introduction à la psychopathologie de l’adulte",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-adulte/cm05-06-dsm.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-adulte-cm05-06-dsm"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-adulte-cm07-nevrose-obsessionel",
    "slug": "cm07-nevrose-obsessionel.md",
    "title": "CM07 — Névrose obsessionel",
    "module": "CM — Introduction à la psychopathologie de l’adulte",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 5,
    "description": "Névrose obsessionnelle Historique La névrose obsessionnelle vient du mot « assiéger » C’est le développement d’une théorie de cette névrose par Freud et Janet en parallèle de l’hystérie. « se définit par le caractère forcé (compulsions) de sentiments, d’idées…",
    "themes": [
      "Psychopathologie",
      "Adulte"
    ],
    "keywords": [
      "CM07 — Névrose obsessionel",
      "UE1 - Psychologie clinique/Introduction à la psychopathologie de l_adulte/CM07 - Névrose obsessionel.docx",
      "CM — Introduction à la psychopathologie de l’adulte",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Introduction à la psychopathologie de l’adulte",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-adulte/cm07-nevrose-obsessionel.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-adulte-cm07-nevrose-obsessionel"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-adulte-cm07-08-nevrose-d-angoisse-et-nevrose-phobique",
    "slug": "cm07-08-nevrose-d-angoisse-et-nevrose-phobique.md",
    "title": "CM07-08 — Névrose d angoisse & névrose phobique",
    "module": "CM — Introduction à la psychopathologie de l’adulte",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 6,
    "description": "Névrose d’angoisse et névrose phobique Angoisse Ango = serrer Dans le sens commun, l’angoisse est une peur sans objet déterminé. La peur aurait un objet déterminé. Dans l’introduction à la psychanalyse (1916), Freud distingue 2 types d’angoisse : angoisse réel…",
    "themes": [
      "Psychopathologie",
      "Adulte"
    ],
    "keywords": [
      "CM07-08 — Névrose d angoisse & névrose phobique",
      "UE1 - Psychologie clinique/Introduction à la psychopathologie de l_adulte/CM07-08 - Névrose d_angoisse & névrose phobique.docx",
      "CM — Introduction à la psychopathologie de l’adulte",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Introduction à la psychopathologie de l’adulte",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-adulte/cm07-08-nevrose-d-angoisse-et-nevrose-phobique.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-adulte-cm07-08-nevrose-d-angoisse-et-nevrose-phobique"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-adulte-cm08-psychose",
    "slug": "cm08-psychose.md",
    "title": "CM08 — Psychose",
    "module": "CM — Introduction à la psychopathologie de l’adulte",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 7,
    "description": "Les psychoses Introduction Le terme psychose désigne des états psychiques caractérisés par une altération profonde de la conscience du sujet (troubles graves de l’identité) et dans son rapport à la réalité. La structure psychotique renvoie à un mode d’organisa…",
    "themes": [
      "Psychopathologie",
      "Adulte"
    ],
    "keywords": [
      "CM08 — Psychose",
      "UE1 - Psychologie clinique/Introduction à la psychopathologie de l_adulte/CM08 - Psychose.docx",
      "CM — Introduction à la psychopathologie de l’adulte",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Introduction à la psychopathologie de l’adulte",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-adulte/cm08-psychose.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-adulte-cm08-psychose"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-adulte-cm09-10-la-schizophrenie",
    "slug": "cm09-10-la-schizophrenie.md",
    "title": "CM09-10 — La schizophrénie",
    "module": "CM — Introduction à la psychopathologie de l’adulte",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 8,
    "description": "La schizophrénie Introduction La schizophrénie touche 1% population générale Elle a longtemps été appelé démence précoce (Kraeplin) C’est un terme inventé par Bleuler (1911) : Vient du grec skizein = fendre, déchirer et : phrên = esprit, coeur La schizophrénie…",
    "themes": [
      "Psychopathologie",
      "Adulte"
    ],
    "keywords": [
      "CM09-10 — La schizophrénie",
      "UE1 - Psychologie clinique/Introduction à la psychopathologie de l_adulte/CM09-10 - La schizophrénie.docx",
      "CM — Introduction à la psychopathologie de l’adulte",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Introduction à la psychopathologie de l’adulte",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-adulte/cm09-10-la-schizophrenie.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-adulte-cm09-10-la-schizophrenie"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-adulte-cm10-11-la-paranoia",
    "slug": "cm10-11-la-paranoia.md",
    "title": "CM10-11 — La paranoïa",
    "module": "CM — Introduction à la psychopathologie de l’adulte",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 9,
    "description": "La paranoïa Introduction Elle peut souvent être inaperçue. Elle est souvent décrite en opposition à schizophrénie ou avec délires chroniques Terme qui apparaît en 1879 avec Krafft-Ebing « développement insidieux sous la dépendance de causes internes et selon u…",
    "themes": [
      "Psychopathologie",
      "Adulte"
    ],
    "keywords": [
      "CM10-11 — La paranoïa",
      "UE1 - Psychologie clinique/Introduction à la psychopathologie de l_adulte/CM10-11 - La paranoïa.docx",
      "CM — Introduction à la psychopathologie de l’adulte",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Introduction à la psychopathologie de l’adulte",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-adulte/cm10-11-la-paranoia.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-adulte-cm10-11-la-paranoia"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-adulte-cm11-trouble-maniaco-depressive",
    "slug": "cm11-trouble-maniaco-depressive.md",
    "title": "CM11 — Trouble Maniaco-dépressive",
    "module": "CM — Introduction à la psychopathologie de l’adulte",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 10,
    "description": "Psychose maniaco-dépressives Introduction C’est une alternance d’épisode mélancolique et maniaque (manie). D’une manière historique : - Manie et mélancolie connu depuis antiquité - Reconnaissance de leurs liens en une seule pathologie en 1854 : L’un disait que…",
    "themes": [
      "Psychopathologie",
      "Adulte"
    ],
    "keywords": [
      "CM11 — Trouble Maniaco-dépressive",
      "UE1 - Psychologie clinique/Introduction à la psychopathologie de l_adulte/CM11 - Trouble Maniaco-dépressive.docx",
      "CM — Introduction à la psychopathologie de l’adulte",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Introduction à la psychopathologie de l’adulte",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-adulte/cm11-trouble-maniaco-depressive.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-adulte-cm11-trouble-maniaco-depressive"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-adulte-cm12-tcc",
    "slug": "cm12-tcc.md",
    "title": "CM12 — TCC",
    "module": "CM — Introduction à la psychopathologie de l’adulte",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 11,
    "description": "Le psychothérapies cognitivo-comportementales Introduction C’est l’application de la psychologie scientifique à la psychothérapie : méthodes expérimentale. Pathologies ont plusieurs causes, on ne peut réduire une pathologie à une seule cause. Notre environneme…",
    "themes": [
      "Psychopathologie",
      "Adulte"
    ],
    "keywords": [
      "CM12 — TCC",
      "UE1 - Psychologie clinique/Introduction à la psychopathologie de l_adulte/CM12 - TCC.docx",
      "CM — Introduction à la psychopathologie de l’adulte",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Introduction à la psychopathologie de l’adulte",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-adulte/cm12-tcc.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-adulte-cm12-tcc"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-enfant-adolescent-cm01-02-principaux-reperes-historiques-du-developpement-de-la-psychopathologie-de-l-enfant",
    "slug": "cm01-02-principaux-reperes-historiques-du-developpement-de-la-psychopathologie-de-l-enfant.md",
    "title": "CM01-02 — Principaux repères historiques du développement de la psychopathologie de l enfant",
    "module": "CM — Psychopathologie de l’enfant et de l’adolescent",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 12,
    "description": "Psychopathologie de l’enfant et de l’adolescent Auteurs que l’on devrait lire : - Sigmund FREUD - René SPITZ (créateur de l’hospitalise : structure qui accueille enfant abandonné, qui développait pathologie profonde, carences…) - John BOWLBY (cf. théorie de l’…",
    "themes": [
      "Psychopathologie",
      "Enfant",
      "Adolescent"
    ],
    "keywords": [
      "CM01-02 — Principaux repères historiques du développement de la psychopathologie de l enfant",
      "UE1 - Psychologie clinique/Psychopathologie de l_enfant et de l_adolescent/CM01-02 - Principaux repères historiques du développement de la psychopathologie de l_enfant.docx",
      "CM — Psychopathologie de l’enfant et de l’adolescent",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychopathologie de l’enfant et de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-enfant-adolescent/cm01-02-principaux-reperes-historiques-du-developpement-de-la-psychopathologie-de-l-enfant.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-enfant-adolescent-cm01-02-principaux-reperes-historiques-du-developpement-de-la-psychopathologie-de-l-enfant"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-enfant-adolescent-cm03-04-la-relation-mere-bebe",
    "slug": "cm03-04-la-relation-mere-bebe.md",
    "title": "CM03-04 — La relation Mère-Bébé",
    "module": "CM — Psychopathologie de l’enfant et de l’adolescent",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 13,
    "description": "La relation Mère-Bébé Au début du XX, le bébé était considéré comme une larve. On faisait beaucoup d’enfant pour qu’au moins un survive. Aujourd’hui, quand on en a un enfant, il a toutes les chances de survivre. On pense aujourd’hui que le bébé n’est pas une l…",
    "themes": [
      "Psychopathologie",
      "Enfant",
      "Adolescent"
    ],
    "keywords": [
      "CM03-04 — La relation Mère-Bébé",
      "UE1 - Psychologie clinique/Psychopathologie de l_enfant et de l_adolescent/CM03-04 - La relation Mère-Bébé.docx",
      "CM — Psychopathologie de l’enfant et de l’adolescent",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychopathologie de l’enfant et de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-enfant-adolescent/cm03-04-la-relation-mere-bebe.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-enfant-adolescent-cm03-04-la-relation-mere-bebe"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-enfant-adolescent-cm05-06-l-enfant-en-danger",
    "slug": "cm05-06-l-enfant-en-danger.md",
    "title": "CM05-06 — L enfant en danger",
    "module": "CM — Psychopathologie de l’enfant et de l’adolescent",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 14,
    "description": "L’enfant en danger Le cours est basé sur le savoir de Léon KREISLER. Organisation psychosomatique Les enfants victimes de sévices Organisation psychosomatique Qu’est-ce que les troubles psychosomatiques ? Elles présentent deux versants : l’un médical (somatiqu…",
    "themes": [
      "Psychopathologie",
      "Enfant",
      "Adolescent"
    ],
    "keywords": [
      "CM05-06 — L enfant en danger",
      "UE1 - Psychologie clinique/Psychopathologie de l_enfant et de l_adolescent/CM05-06 - L_enfant en danger.docx",
      "CM — Psychopathologie de l’enfant et de l’adolescent",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychopathologie de l’enfant et de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-enfant-adolescent/cm05-06-l-enfant-en-danger.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-enfant-adolescent-cm05-06-l-enfant-en-danger"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-enfant-adolescent-cm06-07-la-theorie-freudienne-du-developpement-de-la-personnalite",
    "slug": "cm06-07-la-theorie-freudienne-du-developpement-de-la-personnalite.md",
    "title": "CM06-07 — La théorie freudienne du développement de la personnalité",
    "module": "CM — Psychopathologie de l’enfant et de l’adolescent",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 15,
    "description": "La théorie freudienne du développement de la personnalité Freud a fait des hypothèses, à une façon de voir les choses mais cependant, nous n’avons pas de preuve qui prouveraient la chose. Il a discerné les stades prégénitaux, à développer des phases de latence…",
    "themes": [
      "Psychopathologie",
      "Enfant",
      "Adolescent"
    ],
    "keywords": [
      "CM06-07 — La théorie freudienne du développement de la personnalité",
      "UE1 - Psychologie clinique/Psychopathologie de l_enfant et de l_adolescent/CM06-07 - La théorie freudienne du développement de la personnalité.docx",
      "CM — Psychopathologie de l’enfant et de l’adolescent",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychopathologie de l’enfant et de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-enfant-adolescent/cm06-07-la-theorie-freudienne-du-developpement-de-la-personnalite.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-enfant-adolescent-cm06-07-la-theorie-freudienne-du-developpement-de-la-personnalite"
  },
  {
    "id": "cours:psy-l1-s3-ue1-psychopathologie-enfant-adolescent-cm07-10-pathologies",
    "slug": "cm07-10-pathologies.md",
    "title": "CM07-10 — Pathologies",
    "module": "CM — Psychopathologie de l’enfant et de l’adolescent",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 16,
    "description": "Pathologies Psychoses infantiles La majorité des auteurs distinguent les psychoses précoces et celle de la seconde. Psychoses précoces L’autisme de Kanner Il y a autant d’autisme que d’autiste. Par conséquence, il vaut mieux avoir une référence. Il s’agit de l…",
    "themes": [
      "Psychopathologie",
      "Enfant",
      "Adolescent"
    ],
    "keywords": [
      "CM07-10 — Pathologies",
      "UE1 - Psychologie clinique/Psychopathologie de l_enfant et de l_adolescent/CM07-10 - Pathologies.docx",
      "CM — Psychopathologie de l’enfant et de l’adolescent",
      "UE1 — Psychologie clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE1 — Psychologie clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychopathologie de l’enfant et de l’adolescent",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue1/psychopathologie-enfant-adolescent/cm07-10-pathologies.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue1-psychopathologie-enfant-adolescent-cm07-10-pathologies"
  },
  {
    "id": "cours:psy-l1-s3-ue2-psychologie-du-travail-cm01-03-introduction-a-la-psychologie-du-travail-version-2",
    "slug": "cm01-03-introduction-a-la-psychologie-du-travail-version-2.md",
    "title": "CM01-03 — Introduction à la psychologie du travail — version 2",
    "module": "CM — Psychologie du travail",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 17,
    "description": "Introduction à la psychologie du travail Définition, objets et rapports avec les séances voisines Quel est l’objet de la psychologie du travail ? La psychologie du travail est une division de la psychologie. Elle s’occuper de problématique lié au travail. Son…",
    "themes": [
      "Psychologie du travail",
      "Ergonomie",
      "Organisation"
    ],
    "keywords": [
      "CM01-03 — Introduction à la psychologie du travail — version 2",
      "UE2 - Psychologie sociale et Travail/Psychologie du travail/CM01-03 - Introduction à la psychologie du travail(1).docx",
      "CM — Psychologie du travail",
      "UE2 — Psychologie sociale & travail",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE2 — Psychologie sociale & travail",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue2/psychologie-du-travail/cm01-03-introduction-a-la-psychologie-du-travail-version-2.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue2-psychologie-du-travail-cm01-03-introduction-a-la-psychologie-du-travail-version-2"
  },
  {
    "id": "cours:psy-l1-s3-ue2-psychologie-du-travail-cm01-03-introduction-a-la-psychologie-du-travail",
    "slug": "cm01-03-introduction-a-la-psychologie-du-travail.md",
    "title": "CM01-03 — Introduction à la psychologie du travail",
    "module": "CM — Psychologie du travail",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 18,
    "description": "Introduction à la psychologie du travail Définition, objets et rapports avec les séances voisines Quel est l’objet de la psychologie du travail ? La psychologie du travail est une division de la psychologie. Elle s’occuper de problématique lié au travail. Son…",
    "themes": [
      "Psychologie du travail",
      "Ergonomie",
      "Organisation"
    ],
    "keywords": [
      "CM01-03 — Introduction à la psychologie du travail",
      "UE2 - Psychologie sociale et Travail/Psychologie du travail/CM01-03 - Introduction à la psychologie du travail.docx",
      "CM — Psychologie du travail",
      "UE2 — Psychologie sociale & travail",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE2 — Psychologie sociale & travail",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue2/psychologie-du-travail/cm01-03-introduction-a-la-psychologie-du-travail.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue2-psychologie-du-travail-cm01-03-introduction-a-la-psychologie-du-travail"
  },
  {
    "id": "cours:psy-l1-s3-ue2-psychologie-du-travail-cm04-la-motivation-au-travail-version-2",
    "slug": "cm04-la-motivation-au-travail-version-2.md",
    "title": "CM04 — La motivation au travail — version 2",
    "module": "CM — Psychologie du travail",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 19,
    "description": "La motivation au travail Le lieu du travail est devenu un objet d’étude à part entière. On s’est intéressé à la motivation au travail à partir de la deuxième partie du XX°. Des chefs d’entreprises sont venus voir les psychologues du travail pour étudier la mot…",
    "themes": [
      "Psychologie du travail",
      "Ergonomie",
      "Organisation"
    ],
    "keywords": [
      "CM04 — La motivation au travail — version 2",
      "UE2 - Psychologie sociale et Travail/Psychologie du travail/CM04 - La motivation au travail(1).docx",
      "CM — Psychologie du travail",
      "UE2 — Psychologie sociale & travail",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE2 — Psychologie sociale & travail",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue2/psychologie-du-travail/cm04-la-motivation-au-travail-version-2.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue2-psychologie-du-travail-cm04-la-motivation-au-travail-version-2"
  },
  {
    "id": "cours:psy-l1-s3-ue2-psychologie-du-travail-cm04-la-motivation-au-travail",
    "slug": "cm04-la-motivation-au-travail.md",
    "title": "CM04 — La motivation au travail",
    "module": "CM — Psychologie du travail",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 20,
    "description": "La motivation au travail Le lieu du travail est devenu un objet d’étude à part entière. On s’est intéressé à la motivation au travail à partir de la deuxième partie du XX°. Des chefs d’entreprises sont venus voir les psychologues du travail pour étudier la mot…",
    "themes": [
      "Psychologie du travail",
      "Ergonomie",
      "Organisation"
    ],
    "keywords": [
      "CM04 — La motivation au travail",
      "UE2 - Psychologie sociale et Travail/Psychologie du travail/CM04 - La motivation au travail.docx",
      "CM — Psychologie du travail",
      "UE2 — Psychologie sociale & travail",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE2 — Psychologie sociale & travail",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue2/psychologie-du-travail/cm04-la-motivation-au-travail.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue2-psychologie-du-travail-cm04-la-motivation-au-travail"
  },
  {
    "id": "cours:psy-l1-s3-ue2-psychologie-du-travail-cm05-le-leadership-version-2",
    "slug": "cm05-le-leadership-version-2.md",
    "title": "CM05 — Le leadership — version 2",
    "module": "CM — Psychologie du travail",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 21,
    "description": "Le leadership On va avoir des plusieurs concepts à la base du leadership : - Influence sociale - L’autorité - Le délégué - Le chef - Le lead Introduction Le leadership est X Quelques concepts de psychologie sociale Expérience de psychologie sociale. On va d’ab…",
    "themes": [
      "Psychologie du travail",
      "Ergonomie",
      "Organisation"
    ],
    "keywords": [
      "CM05 — Le leadership — version 2",
      "UE2 - Psychologie sociale et Travail/Psychologie du travail/CM05 - Le leadership(1).docx",
      "CM — Psychologie du travail",
      "UE2 — Psychologie sociale & travail",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE2 — Psychologie sociale & travail",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue2/psychologie-du-travail/cm05-le-leadership-version-2.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue2-psychologie-du-travail-cm05-le-leadership-version-2"
  },
  {
    "id": "cours:psy-l1-s3-ue2-psychologie-du-travail-cm05-le-leadership",
    "slug": "cm05-le-leadership.md",
    "title": "CM05 — Le leadership",
    "module": "CM — Psychologie du travail",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 22,
    "description": "Le leadership On va avoir des plusieurs concepts à la base du leadership : - Influence sociale - L’autorité - Le délégué - Le chef - Le lead Introduction Le leadership est X Quelques concepts de psychologie sociale Expérience de psychologie sociale. On va d’ab…",
    "themes": [
      "Psychologie du travail",
      "Ergonomie",
      "Organisation"
    ],
    "keywords": [
      "CM05 — Le leadership",
      "UE2 - Psychologie sociale et Travail/Psychologie du travail/CM05 - Le leadership.docx",
      "CM — Psychologie du travail",
      "UE2 — Psychologie sociale & travail",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE2 — Psychologie sociale & travail",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue2/psychologie-du-travail/cm05-le-leadership.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue2-psychologie-du-travail-cm05-le-leadership"
  },
  {
    "id": "cours:psy-l1-s3-ue2-psychologie-du-travail-cm06-le-management-des-organisations",
    "slug": "cm06-le-management-des-organisations.md",
    "title": "CM06 — Le management des organisations",
    "module": "CM — Psychologie du travail",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 23,
    "description": "Le management des organisations Qu’est-ce que manager ? L’homme et l’organisation : les approches Activités et compétences du manager Le management des ressources humaines Qu’est-ce que manager ? Cadre : statut donné à certains salariés leur permettant l’accès…",
    "themes": [
      "Psychologie du travail",
      "Ergonomie",
      "Organisation"
    ],
    "keywords": [
      "CM06 — Le management des organisations",
      "UE2 - Psychologie sociale et Travail/Psychologie du travail/CM06 - Le management des organisations.docx",
      "CM — Psychologie du travail",
      "UE2 — Psychologie sociale & travail",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE2 — Psychologie sociale & travail",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue2/psychologie-du-travail/cm06-le-management-des-organisations.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue2-psychologie-du-travail-cm06-le-management-des-organisations"
  },
  {
    "id": "cours:psy-l1-s3-ue2-psychologie-du-travail-cm07-introduction-a-la-psychologie-du-travail-et-a-l-ergonomie",
    "slug": "cm07-introduction-a-la-psychologie-du-travail-et-a-l-ergonomie.md",
    "title": "CM07 — Introduction à la psychologie du travail et à l ergonomie",
    "module": "CM — Psychologie du travail",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 24,
    "description": "Introduction à la psychologie du travail et à l’Ergonomie Définition de l’ergonomie L’ergonomie va être appréhendée par les personnes avec plusieurs concepts : - Rpport H/T, santé, bien-être 30% - Science du travail 23 - Meilleure organisation / performance 8…",
    "themes": [
      "Psychologie du travail",
      "Ergonomie",
      "Organisation"
    ],
    "keywords": [
      "CM07 — Introduction à la psychologie du travail et à l ergonomie",
      "UE2 - Psychologie sociale et Travail/Psychologie du travail/CM07 - Introduction à la psychologie du travail et à l_ergonomie.docx",
      "CM — Psychologie du travail",
      "UE2 — Psychologie sociale & travail",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE2 — Psychologie sociale & travail",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue2/psychologie-du-travail/cm07-introduction-a-la-psychologie-du-travail-et-a-l-ergonomie.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue2-psychologie-du-travail-cm07-introduction-a-la-psychologie-du-travail-et-a-l-ergonomie"
  },
  {
    "id": "cours:psy-l1-s3-ue2-psychologie-du-travail-cm07-09-introduction-a-la-psychologie-du-travail-et-a-l-ergonomie",
    "slug": "cm07-09-introduction-a-la-psychologie-du-travail-et-a-l-ergonomie.md",
    "title": "CM07-09 — Introduction à la psychologie du travail et à l ergonomie",
    "module": "CM — Psychologie du travail",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 25,
    "description": "Introduction à la psychologie du travail et à l’Ergonomie Définition de l’ergonomie L’ergonomie va être appréhendée par les personnes avec plusieurs concepts : - Rpport H/T, santé, bien-être 30% - Science du travail 23 - Meilleure organisation / performance 8…",
    "themes": [
      "Psychologie du travail",
      "Ergonomie",
      "Organisation"
    ],
    "keywords": [
      "CM07-09 — Introduction à la psychologie du travail et à l ergonomie",
      "UE2 - Psychologie sociale et Travail/Psychologie du travail/CM07-09 - Introduction à la psychologie du travail et à l_ergonomie.docx",
      "CM — Psychologie du travail",
      "UE2 — Psychologie sociale & travail",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE2 — Psychologie sociale & travail",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du travail",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue2/psychologie-du-travail/cm07-09-introduction-a-la-psychologie-du-travail-et-a-l-ergonomie.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue2-psychologie-du-travail-cm07-09-introduction-a-la-psychologie-du-travail-et-a-l-ergonomie"
  },
  {
    "id": "cours:psy-l1-s3-ue2-psychologie-sociale-cm01-12-violence-et-agression-modele-explicatifs",
    "slug": "cm01-12-violence-et-agression-modele-explicatifs.md",
    "title": "CM01-12 — Violence et agression - modèle explicatifs",
    "module": "CM — Psychologie sociale",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 26,
    "description": "Violence et agression : modèle explicatifs Il est difficile en tant que chercheur de ne pas se sentir lié à son sujet. Un livre de Laurent Obertone est sorti il y a plusieurs années : « la France orange mécanique ». On va avoir des périodes de paniques morales…",
    "themes": [
      "Psychologie sociale",
      "Violence",
      "Agression"
    ],
    "keywords": [
      "CM01-12 — Violence et agression - modèle explicatifs",
      "UE2 - Psychologie sociale et Travail/Psychologie sociale/CM01-12 - Violence et agression - modèle explicatifs.docx",
      "CM — Psychologie sociale",
      "UE2 — Psychologie sociale & travail",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE2 — Psychologie sociale & travail",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie sociale",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue2/psychologie-sociale/cm01-12-violence-et-agression-modele-explicatifs.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue2-psychologie-sociale-cm01-12-violence-et-agression-modele-explicatifs"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-cognitive-cm01-methodologie-experimentale",
    "slug": "cm01-methodologie-experimentale.md",
    "title": "CM01 — Méthodologie expérimentale",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 27,
    "description": "Méthodologie expérimentale On veut démontrer expérimentalement ce que l’on veut prouver. On s’intéresse à des domaines particuliers pour prouver certaines choses. La démarche scientifique consiste globalement à être en 4 étapes : - Observation : théories, modè…",
    "themes": [
      "Psychologie cognitive",
      "Perception",
      "Langage"
    ],
    "keywords": [
      "CM01 — Méthodologie expérimentale",
      "UE3 - Psychologie cognitive et Développement/Psychologie cognitive/CM01 - Méthodologie expérimentale.docx",
      "CM — Psychologie cognitive",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-cognitive/cm01-methodologie-experimentale.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-cognitive-cm01-methodologie-experimentale"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-cognitive-cm02-perception-auditive",
    "slug": "cm02-perception-auditive.md",
    "title": "CM02 — Perception auditive",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 28,
    "description": "Perception auditive La structure physique des sons Le son est un objet qui vibre. Une vibration est un déplacement répété en va et vient d’un objet. La vibration va provoquer le son. La vibration est produite par le retour à l’état d’équilibre. La vibration es…",
    "themes": [
      "Psychologie cognitive",
      "Perception",
      "Langage"
    ],
    "keywords": [
      "CM02 — Perception auditive",
      "UE3 - Psychologie cognitive et Développement/Psychologie cognitive/CM02 - Perception auditive.docx",
      "CM — Psychologie cognitive",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-cognitive/cm02-perception-auditive.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-cognitive-cm02-perception-auditive"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-cognitive-cm03-04-methode-de-mesures-de-seuil",
    "slug": "cm03-04-methode-de-mesures-de-seuil.md",
    "title": "CM03-04 — Méthode de mesures de seuil",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 29,
    "description": "L’analyse des scènes auditives Il existe des problèmes de l’audition : - Organisation simultanée - Organisation séquentielle Ainsi, nous avons plusieurs attributs sonores : - Perception de la hauteur - Perception de l’intensité - Perception du timbre - Localis…",
    "themes": [
      "Psychologie cognitive",
      "Perception",
      "Langage"
    ],
    "keywords": [
      "CM03-04 — Méthode de mesures de seuil",
      "UE3 - Psychologie cognitive et Développement/Psychologie cognitive/CM03-04 - Méthode de mesures de seuil.docx",
      "CM — Psychologie cognitive",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-cognitive/cm03-04-methode-de-mesures-de-seuil.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-cognitive-cm03-04-methode-de-mesures-de-seuil"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-cognitive-cm05-06-perception-de-la-parole",
    "slug": "cm05-06-perception-de-la-parole.md",
    "title": "CM05-06 — Perception de la parole",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 30,
    "description": "Perception de la parole Un des aspects fondamental de la perception de la parole est de pouvoir accéder à des perceptions de mots. Lorsque l’on parle, il faut que les autres personnes puissent reconnaitre les mots que l’on dit et qu’on puisse reconnaitre le si…",
    "themes": [
      "Psychologie cognitive",
      "Perception",
      "Langage"
    ],
    "keywords": [
      "CM05-06 — Perception de la parole",
      "UE3 - Psychologie cognitive et Développement/Psychologie cognitive/CM05-06 - Perception de la parole.docx",
      "CM — Psychologie cognitive",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-cognitive/cm05-06-perception-de-la-parole.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-cognitive-cm05-06-perception-de-la-parole"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-cognitive-cm07-08-acquisition-du-langage",
    "slug": "cm07-08-acquisition-du-langage.md",
    "title": "CM07-08 — Acquisition du langage",
    "module": "CM — Psychologie cognitive",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 31,
    "description": "Acquisition du langage Introduction L’enfant doit organiser les ifnoramtions sensorielles qu’il reçoit de son entourage. L’enfant va être baigné dans un environnement linguistique & sonore. Il va devoir organiser ce qu’il entend. Il va falloir extraire l’infor…",
    "themes": [
      "Psychologie cognitive",
      "Perception",
      "Langage"
    ],
    "keywords": [
      "CM07-08 — Acquisition du langage",
      "UE3 - Psychologie cognitive et Développement/Psychologie cognitive/CM07-08 - Acquisition du langage.docx",
      "CM — Psychologie cognitive",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie cognitive",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-cognitive/cm07-08-acquisition-du-langage.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-cognitive-cm07-08-acquisition-du-langage"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-du-developpement-cm01-02-introduction-a-la-theorie-de-jean-piaget",
    "slug": "cm01-02-introduction-a-la-theorie-de-jean-piaget.md",
    "title": "CM01-02 — Introduction à la théorie de Jean Piaget",
    "module": "CM — Psychologie du développement",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 32,
    "description": "Psychologie du développement Bibliographie générale : - Bideaud, J., Houdé, O. &amp; Pedinielli, J.-L. (2004). L’homme en développement. Paris : PUF. - Blaye, A. &amp; Lemaire, P. (2007). Psychologie du développement cognitif de l’enfant. Bruxelles : DeBoeck…",
    "themes": [
      "Psychologie du développement",
      "Piaget",
      "Développement cognitif"
    ],
    "keywords": [
      "CM01-02 — Introduction à la théorie de Jean Piaget",
      "UE3 - Psychologie cognitive et Développement/Psychologie du développement/CM01-02 - Introduction à la théorie de Jean Piaget.docx",
      "CM — Psychologie du développement",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du développement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-du-developpement/cm01-02-introduction-a-la-theorie-de-jean-piaget.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-du-developpement-cm01-02-introduction-a-la-theorie-de-jean-piaget"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-du-developpement-cm02-03-stade-sensori-moteur",
    "slug": "cm02-03-stade-sensori-moteur.md",
    "title": "CM02-03 — Stade sensori-moteur",
    "module": "CM — Psychologie du développement",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 33,
    "description": "Stade sensori-moteur PIAGET va essayer de voir les prémisses de l’intelligence (0 à 2 ans). A quel moment va-t-on pouvoir parler d’intelligence. Pour PIAGET, le développement cognitif est basé sur la sensorialité (ce qu’il perçoit) et d’autre part sur ces acti…",
    "themes": [
      "Psychologie du développement",
      "Piaget",
      "Développement cognitif"
    ],
    "keywords": [
      "CM02-03 — Stade sensori-moteur",
      "UE3 - Psychologie cognitive et Développement/Psychologie du développement/CM02-03 - Stade sensori-moteur.docx",
      "CM — Psychologie du développement",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du développement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-du-developpement/cm02-03-stade-sensori-moteur.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-du-developpement-cm02-03-stade-sensori-moteur"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-du-developpement-cm03-04-stade-preoperatoire-et-operatoire-concret",
    "slug": "cm03-04-stade-preoperatoire-et-operatoire-concret.md",
    "title": "CM03-04 — Stade préopératoire et opératoire concret",
    "module": "CM — Psychologie du développement",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 34,
    "description": "Stade préopératoire Bibliographie : - Siegler, R.S (2001). Enfant et raisonnement. Bruxelles : De Boeck Université (P. 35-75) Apparition de la fonction symbolique Définition Fonction symbolique = intelligence représentative Fonction symbolique : capacité d’évo…",
    "themes": [
      "Psychologie du développement",
      "Piaget",
      "Développement cognitif"
    ],
    "keywords": [
      "CM03-04 — Stade préopératoire et opératoire concret",
      "UE3 - Psychologie cognitive et Développement/Psychologie du développement/CM03-04 - Stade préopératoire et opératoire concret.docx",
      "CM — Psychologie du développement",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du développement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-du-developpement/cm03-04-stade-preoperatoire-et-operatoire-concret.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-du-developpement-cm03-04-stade-preoperatoire-et-operatoire-concret"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-du-developpement-cm04-stade-operatoire-formel",
    "slug": "cm04-stade-operatoire-formel.md",
    "title": "CM04 — Stade opératoire formel",
    "module": "CM — Psychologie du développement",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 35,
    "description": "Stade opératoire formel Il se commence vers 11/12 ans et se termine vers 14/15 ans. Il y a des grandes différences interindividuelles sur ce stade. C’est un stade qui n’est pas atteint par tous les adultes. Ce qui va marquer cette étape est le raisonnement hyp…",
    "themes": [
      "Psychologie du développement",
      "Piaget",
      "Développement cognitif"
    ],
    "keywords": [
      "CM04 — Stade opératoire formel",
      "UE3 - Psychologie cognitive et Développement/Psychologie du développement/CM04 - Stade opératoire formel.docx",
      "CM — Psychologie du développement",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du développement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-du-developpement/cm04-stade-operatoire-formel.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-du-developpement-cm04-stade-operatoire-formel"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-du-developpement-cm05-06-psychologie-sociale-du-developpement-cognitif",
    "slug": "cm05-06-psychologie-sociale-du-developpement-cognitif.md",
    "title": "CM05-06 — Psychologie sociale du développement cognitif",
    "module": "CM — Psychologie du développement",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 36,
    "description": "Psychologie sociale du développement cognitif Bibliographie : - Blaye, A. & Lemaire, P. (2007). Psychologie du développement cognitif de l’enfant. Bruxelles, DeBoeck. (Chapitre 10). - Doise, W. & Mugny , G. (1997). Psychologie sociale et développement cognitif…",
    "themes": [
      "Psychologie du développement",
      "Piaget",
      "Développement cognitif"
    ],
    "keywords": [
      "CM05-06 — Psychologie sociale du développement cognitif",
      "UE3 - Psychologie cognitive et Développement/Psychologie du développement/CM05-06 - Psychologie sociale du développement cognitif.docx",
      "CM — Psychologie du développement",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du développement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-du-developpement/cm05-06-psychologie-sociale-du-developpement-cognitif.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-du-developpement-cm05-06-psychologie-sociale-du-developpement-cognitif"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-du-developpement-cm06-psychologie-foetale",
    "slug": "cm06-psychologie-foetale.md",
    "title": "CM06 — Psychologie foetale",
    "module": "CM — Psychologie du développement",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 37,
    "description": "Psychologie fœtale Bibliographie : - Lécuyer, R. (2004). Le développement du nourisson Paris, Dunod Chapitre de Granier-Deferre, Schaal & De Casper Quelles stimulations le fœtus et le bébé reçoivent ? Est-ce qu’ils sont sensibles à ses stimulations ? Quelles s…",
    "themes": [
      "Psychologie du développement",
      "Piaget",
      "Développement cognitif"
    ],
    "keywords": [
      "CM06 — Psychologie foetale",
      "UE3 - Psychologie cognitive et Développement/Psychologie du développement/CM06 - Psychologie foetale.docx",
      "CM — Psychologie du développement",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du développement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-du-developpement/cm06-psychologie-foetale.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-du-developpement-cm06-psychologie-foetale"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-du-developpement-cm07-methodes-d-etude-du-bebe",
    "slug": "cm07-methodes-d-etude-du-bebe.md",
    "title": "CM07 — Méthodes d étude du bébé",
    "module": "CM — Psychologie du développement",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 38,
    "description": "Méthode d’étude du bébé Bibliographie : - Pêcheux, M.G. (2006). Les méthodes de la psychologie du développement. In J. Lautrey (Ed.), Psychologie du développement et psychologie différentielle. Paris : PUF. (p. 117-137). - Pêcheux, M.G. & Lécuyer, R. (1999). L…",
    "themes": [
      "Psychologie du développement",
      "Piaget",
      "Développement cognitif"
    ],
    "keywords": [
      "CM07 — Méthodes d étude du bébé",
      "UE3 - Psychologie cognitive et Développement/Psychologie du développement/CM07 - Méthodes d_étude du bébé.docx",
      "CM — Psychologie du développement",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du développement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-du-developpement/cm07-methodes-d-etude-du-bebe.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-du-developpement-cm07-methodes-d-etude-du-bebe"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-du-developpement-cm08-09-competences-precoce-du-bebe",
    "slug": "cm08-09-competences-precoce-du-bebe.md",
    "title": "CM08-09 — Compétences précoce du bébé",
    "module": "CM — Psychologie du développement",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 39,
    "description": "Compétences précoces du bébé Bibliographie : - Stéri, A (2006) Développement de la représentation des objets. In J.Lautry. Psychologie du XXX Les compétences des bébés sont étudiées dans de nombreux domaines. Nous allons étudier l’imitation et l’intermodalité…",
    "themes": [
      "Psychologie du développement",
      "Piaget",
      "Développement cognitif"
    ],
    "keywords": [
      "CM08-09 — Compétences précoce du bébé",
      "UE3 - Psychologie cognitive et Développement/Psychologie du développement/CM08-09 - Compétences précoce du bébé.docx",
      "CM — Psychologie du développement",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du développement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-du-developpement/cm08-09-competences-precoce-du-bebe.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-du-developpement-cm08-09-competences-precoce-du-bebe"
  },
  {
    "id": "cours:psy-l1-s3-ue3-psychologie-du-developpement-cm09-developpement-cognitif-et-education",
    "slug": "cm09-developpement-cognitif-et-education.md",
    "title": "CM09 — Développement cognitif et éducation",
    "module": "CM — Psychologie du développement",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 40,
    "description": "Développement cognitif et éducation Bibliographie : - Lautrey, J. (1980) Classe sociale, milieu familial, intelligence. Paris : PUF Le point de départ de l’étude est que l’on observe un lien entre la réussite aux test d’intelligence et la classe sociale. Les p…",
    "themes": [
      "Psychologie du développement",
      "Piaget",
      "Développement cognitif"
    ],
    "keywords": [
      "CM09 — Développement cognitif et éducation",
      "UE3 - Psychologie cognitive et Développement/Psychologie du développement/CM09 - Développement cognitif et éducation.docx",
      "CM — Psychologie du développement",
      "UE3 — Psychologie cognitive & développement",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE3 — Psychologie cognitive & développement",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Psychologie du développement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue3/psychologie-du-developpement/cm09-developpement-cognitif-et-education.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue3-psychologie-du-developpement-cm09-developpement-cognitif-et-education"
  },
  {
    "id": "cours:psy-l1-s3-ue4-traitement-des-donnees-cm01-introduction-traitement-de-donnees",
    "slug": "cm01-introduction-traitement-de-donnees.md",
    "title": "CM01 — Introduction traitement de données",
    "module": "CM — Traitement de données",
    "courseTheme": "methodologie",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 41,
    "description": "Introduction Traitement de données Des statistiques descriptives (L1) aux statistiques inférentielles (L3) La différence avec la L1 est que les statistiques passent du particulier au général, de l’échantillon à la population. Le cours à divers objectif : Rappe…",
    "themes": [
      "Méthodologie",
      "Traitement de données",
      "Statistiques"
    ],
    "keywords": [
      "CM01 — Introduction traitement de données",
      "UE4 - Outils/Traitement de données/CM01 - Introduction traitement de données.docx",
      "CM — Traitement de données",
      "UE4 — Outils",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE4 — Outils",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Traitement de données",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue4/traitement-des-donnees/cm01-introduction-traitement-de-donnees.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue4-traitement-des-donnees-cm01-introduction-traitement-de-donnees"
  },
  {
    "id": "cours:psy-l1-s3-ue5-ethologie-et-chronobiologie-cm01-04-chronobiologie",
    "slug": "cm01-04-chronobiologie.md",
    "title": "CM01-04 — Chronobiologie",
    "module": "CM — Éthologie & chronobiologie",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 42,
    "description": "Ethologie & Chronobiologie Chrono = le temps / Biologie = l’étude du vivant La chronobiologie est l’étude des rythmes biologiques (rythmes périodiques). Rythme & temporalité Temporalité = dimension temporelle Dans la temporalité s’inscrit des rythmes. Rythme a…",
    "themes": [
      "Biologie",
      "Éthologie",
      "Chronobiologie"
    ],
    "keywords": [
      "CM01-04 — Chronobiologie",
      "UE5 - Base de biologie/Ethologie et chronobiologie/CM01-04 - Chronobiologie.docx",
      "CM — Éthologie & chronobiologie",
      "UE5 — Bases de biologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE5 — Bases de biologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Éthologie & chronobiologie",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue5/ethologie-et-chronobiologie/cm01-04-chronobiologie.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue5-ethologie-et-chronobiologie-cm01-04-chronobiologie"
  },
  {
    "id": "cours:psy-l1-s3-ue5-ethologie-et-chronobiologie-cm05-08-ethologie",
    "slug": "cm05-08-ethologie.md",
    "title": "CM05-08 — Ethologie",
    "module": "CM — Éthologie & chronobiologie",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 43,
    "description": "Ethologie Introduction Qu’est-ce que l’éthologie ? Définition Le mot éthologie vient au départ de « discours sur les mœurs animal » Ethos = Moeurs Logos = Raison L’éthologie n’est pas l’étiologie (=étude des causes des maladies) ni de l’ethnologie (=étude des…",
    "themes": [
      "Biologie",
      "Éthologie",
      "Chronobiologie"
    ],
    "keywords": [
      "CM05-08 — Ethologie",
      "UE5 - Base de biologie/Ethologie et chronobiologie/CM05-08 - Ethologie.docx",
      "CM — Éthologie & chronobiologie",
      "UE5 — Bases de biologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE5 — Bases de biologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Éthologie & chronobiologie",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue5/ethologie-et-chronobiologie/cm05-08-ethologie.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue5-ethologie-et-chronobiologie-cm05-08-ethologie"
  },
  {
    "id": "cours:psy-l1-s3-ue5-evolution-et-comportement-cm01-03-biologie-des-populations",
    "slug": "cm01-03-biologie-des-populations.md",
    "title": "CM01-03 — Biologie des populations",
    "module": "CM — Évolution et comportement",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 44,
    "description": "Evolution & comportement Qui suis-je ? D’où je viens ? Il existe plusieurs dimensions de descriptions : - Phylogénèse : (phylogénétique / phylogénique) (genèse : origine // phylo : le clan, la famille, la tribu). C’est un thème de la biologie qui dépend de la…",
    "themes": [
      "Biologie",
      "Évolution",
      "Comportement"
    ],
    "keywords": [
      "CM01-03 — Biologie des populations",
      "UE5 - Base de biologie/Evolution et comportement/CM01-03 - Biologie des populations.docx",
      "CM — Évolution et comportement",
      "UE5 — Bases de biologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE5 — Bases de biologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Évolution et comportement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue5/evolution-et-comportement/cm01-03-biologie-des-populations.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue5-evolution-et-comportement-cm01-03-biologie-des-populations"
  },
  {
    "id": "cours:psy-l1-s3-ue5-evolution-et-comportement-cm03-05-les-mecanismes-de-l-evolution",
    "slug": "cm03-05-les-mecanismes-de-l-evolution.md",
    "title": "CM03-05 — Les mécanismes de l évolution",
    "module": "CM — Évolution et comportement",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 45,
    "description": "Les mécanismes de l’évolution Lamarckisme Quels sont les mécanismes ? Pourquoi les choses ne sont plus les mêmes ? Pourquoi nous avons des êtres si différents les uns des autres ? Lamarckisme « La fonction crée l’organe » La structure se modifie selon la fonct…",
    "themes": [
      "Biologie",
      "Évolution",
      "Comportement"
    ],
    "keywords": [
      "CM03-05 — Les mécanismes de l évolution",
      "UE5 - Base de biologie/Evolution et comportement/CM03-05 - Les mécanismes de l_évolution.docx",
      "CM — Évolution et comportement",
      "UE5 — Bases de biologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE5 — Bases de biologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Évolution et comportement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue5/evolution-et-comportement/cm03-05-les-mecanismes-de-l-evolution.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue5-evolution-et-comportement-cm03-05-les-mecanismes-de-l-evolution"
  },
  {
    "id": "cours:psy-l1-s3-ue5-evolution-et-comportement-cm05-06-neo-darwinisme",
    "slug": "cm05-06-neo-darwinisme.md",
    "title": "CM05-06 — Néo darwinisme",
    "module": "CM — Évolution et comportement",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 46,
    "description": "Néo Darwinisme Le néo darwinisme, aussi appelé la théorie synthétique est tiré de Darwin et plus nouveau que Darwin (cf. Julial Haxley 1942). Rappels & commentaires Le néo darwinisme est la synthèse entre deux courants de la biologie : le darwinisme et la géné…",
    "themes": [
      "Biologie",
      "Évolution",
      "Comportement"
    ],
    "keywords": [
      "CM05-06 — Néo darwinisme",
      "UE5 - Base de biologie/Evolution et comportement/CM05-06 - Néo darwinisme.docx",
      "CM — Évolution et comportement",
      "UE5 — Bases de biologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE5 — Bases de biologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Évolution et comportement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue5/evolution-et-comportement/cm05-06-neo-darwinisme.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue5-evolution-et-comportement-cm05-06-neo-darwinisme"
  },
  {
    "id": "cours:psy-l1-s3-ue5-evolution-et-comportement-cm07-sociobiologie",
    "slug": "cm07-sociobiologie.md",
    "title": "CM07 — Sociobiologie",
    "module": "CM — Évolution et comportement",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 47,
    "description": "Sociobiologie La sociobiologie a été mal vu et a été remplacé par l’éthologie comportementale. La sociobiologie prolonge le raisonnement fondamental darwinisme et de la génétique. C’est une logique un peu implacable. Dimension héréditaire des comportements Les…",
    "themes": [
      "Biologie",
      "Évolution",
      "Comportement"
    ],
    "keywords": [
      "CM07 — Sociobiologie",
      "UE5 - Base de biologie/Evolution et comportement/CM07 - Sociobiologie.docx",
      "CM — Évolution et comportement",
      "UE5 — Bases de biologie",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE5 — Bases de biologie",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Évolution et comportement",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue5/evolution-et-comportement/cm07-sociobiologie.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue5-evolution-et-comportement-cm07-sociobiologie"
  },
  {
    "id": "cours:psy-l1-s3-ue6-ouverture-cm01-02-univers-introduction",
    "slug": "cm01-02-univers-introduction.md",
    "title": "CM01-02 — Univers, introduction",
    "module": "CM — Ouverture",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 48,
    "description": "Univers Nous sommes des irrationnels de nos ennemis. La question est de savoir quelle rationalité nous choisissons. Introduction Cosmo-logie Qu’est-ce que « cosmos » ? C’est l’univers, l’harmonie (=la convenance raisonnable), les bijoux. La structure de la lan…",
    "themes": [
      "Cosmologie",
      "Sciences",
      "Mythes"
    ],
    "keywords": [
      "CM01-02 — Univers, introduction",
      "UE6 - Ouverture/CM01-02 - Univers, introduction.docx",
      "CM — Ouverture",
      "UE6 — Ouverture",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE6 — Ouverture",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Ouverture",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue6/ouverture/cm01-02-univers-introduction.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue6-ouverture-cm01-02-univers-introduction"
  },
  {
    "id": "cours:psy-l1-s3-ue6-ouverture-cm02-03-mythes-et-cosmogonies",
    "slug": "cm02-03-mythes-et-cosmogonies.md",
    "title": "CM02-03 — Mythes et cosmogonies",
    "module": "CM — Ouverture",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 49,
    "description": "Mythes & Cosmogonies Introduction Cosmogonie = récit sur la naissance du cosmo Les mythes ne se sont pas pensés comme des mythes. Est-ce que nous sommes nous-mêmes dans un mythe, une illusion du savoir ? Le mythe était essentiellement décrié. Au XIX°, le roman…",
    "themes": [
      "Cosmologie",
      "Sciences",
      "Mythes"
    ],
    "keywords": [
      "CM02-03 — Mythes et cosmogonies",
      "UE6 - Ouverture/CM02-03 - Mythes et cosmogonies.docx",
      "CM — Ouverture",
      "UE6 — Ouverture",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE6 — Ouverture",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Ouverture",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue6/ouverture/cm02-03-mythes-et-cosmogonies.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue6-ouverture-cm02-03-mythes-et-cosmogonies"
  },
  {
    "id": "cours:psy-l1-s3-ue6-ouverture-cm04-05-big-bang-approche-experimentale",
    "slug": "cm04-05-big-bang-approche-experimentale.md",
    "title": "CM04-05 — Big Bang - approche expérimentale",
    "module": "CM — Ouverture",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 50,
    "description": "Big Bang Taille de l’Univers Si on oublie ce que l’on sait, évaluer la distance des astres est difficile. La taille de l’Univers n’est pas un détail, elle compte. Il faudrait avoir une évaluation un peu quantitative de l’ensemble. - La parallaxe Ce qui rend sc…",
    "themes": [
      "Cosmologie",
      "Sciences",
      "Mythes"
    ],
    "keywords": [
      "CM04-05 — Big Bang - approche expérimentale",
      "UE6 - Ouverture/CM04-05 - Big Bang - approche expérimentale.docx",
      "CM — Ouverture",
      "UE6 — Ouverture",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE6 — Ouverture",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Ouverture",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue6/ouverture/cm04-05-big-bang-approche-experimentale.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue6-ouverture-cm04-05-big-bang-approche-experimentale"
  },
  {
    "id": "cours:psy-l1-s3-ue6-ouverture-cm05-06-big-bang-theorie",
    "slug": "cm05-06-big-bang-theorie.md",
    "title": "CM05-06 — Big Bang - Théorie",
    "module": "CM — Ouverture",
    "courseTheme": "general",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 51,
    "description": "Big Bang Théorie Relativité restreinte Postulat définitoire : il existe des référentiels galiléens dans lesquelles le mouvement libre (quand on est pas soumis à des forces) des corps s’effectue à vitesse constante. D’après Aristote, l’état naturel des choses e…",
    "themes": [
      "Cosmologie",
      "Sciences",
      "Mythes"
    ],
    "keywords": [
      "CM05-06 — Big Bang - Théorie",
      "UE6 - Ouverture/CM05-06 - Big Bang - Théorie.docx",
      "CM — Ouverture",
      "UE6 — Ouverture",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L1",
    "semester": "Semestre 3",
    "ue": "UE6 — Ouverture",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S3",
    "subject": "CM — Ouverture",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l1/s3/ue6/ouverture/cm05-06-big-bang-theorie.md",
    "url": "/mediatheque/cours/?id=psy-l1-s3-ue6-ouverture-cm05-06-big-bang-theorie"
  }
];
  const norm = (v="") => String(v).replace(/\/+$/, "");
  const ids = new Set(DATA.resources.map(x => x && x.id).filter(Boolean));
  const urls = new Set(DATA.resources.map(x => norm(x && x.contentUrl || "")).filter(Boolean));
  let added = 0;
  incoming.forEach(item => {
    if (!item || ids.has(item.id) || urls.has(norm(item.contentUrl))) return;
    DATA.resources.push(item); ids.add(item.id); urls.add(norm(item.contentUrl)); added += 1;
  });
  window.FV_S3_COURSES_STATUS = { ok: true, added, supplied: incoming.length };

  // Merge S3 full-text search with the site's existing index (including prior semester patches).
  if (!window.__FV_S3_FETCH_PATCHED) {
    window.__FV_S3_FETCH_PATCHED = true;
    const nativeFetch = window.fetch.bind(window);
    const scriptUrl = (document.currentScript && document.currentScript.src) || location.href;
    const extraIndexUrl = new URL('./cours/s3-search-index.json', scriptUrl).href;
    window.fetch = async function(input, init) {
      let url = '';
      try { url = typeof input === 'string' ? new URL(input, location.href).href : new URL(input.url, location.href).href; } catch (_) {}
      if (!/\/mediatheque\/cours\/search-index\.json(?:[?#]|$)/.test(url)) return nativeFetch(input, init);
      const [baseResponse, extraResponse] = await Promise.all([
        nativeFetch(input, init).catch(() => null),
        nativeFetch(extraIndexUrl, { cache:'no-store', credentials:'same-origin' }).catch(() => null)
      ]);
      let base={}, extra={};
      try { if (baseResponse && baseResponse.ok) base=await baseResponse.clone().json(); } catch (_) {}
      try { if (extraResponse && extraResponse.ok) extra=await extraResponse.json(); } catch (_) {}
      return new Response(JSON.stringify({ ...base, ...extra }), { status:200, headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'} });
    };
  }
})();
