(() => {
  "use strict";
  const DATA = window.FV_MEDIATHEQUE_DATA || (window.FV_MEDIATHEQUE_DATA = { resources: [], dossiers: [] });
  if (!Array.isArray(DATA.resources)) DATA.resources = [];
  const incoming = [
  {
    "id": "cours:psy-l2-s4-ue1-clinique-de-la-sante-cm01-introduction-a-la-psychologie-de-la-sante",
    "slug": "cm01-introduction-a-la-psychologie-de-la-sante.md",
    "title": "CM01 — Introduction à la Psychologie de la santé",
    "module": "CM — Clinique de la santé",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 1,
    "description": "Introduction à la Psychologie de la santé Bibliographie : Ogden, J (2014) Psychologie de la santé Bruchon Schweitzer, M.Dantazer, R (1994) Introduction à la psychologie de la santé Fischer, G.N. Tarquinio, C. (2002), Trait de psychologie de la santé Fischer, G.N. Tarquinio, C.…",
    "themes": [
      "Santé",
      "Clinique"
    ],
    "keywords": [
      "CM01 — Introduction à la Psychologie de la santé",
      "UE1 - CLINIQUE/CLINIQUE DE LA SANTE/CM01 - Introduction à la Psychologie de la santé.docx",
      "CM — Clinique de la santé",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique de la santé",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/clinique-de-la-sante/cm01-introduction-a-la-psychologie-de-la-sante.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-clinique-de-la-sante-cm01-introduction-a-la-psychologie-de-la-sante"
  },
  {
    "id": "cours:psy-l2-s4-ue1-clinique-de-la-sante-cm02-stress-et-maladies",
    "slug": "cm02-stress-et-maladies.md",
    "title": "CM02 — Stress & Maladies",
    "module": "CM — Clinique de la santé",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 2,
    "description": "Stress & Maladies Qu’est ce que le stress ? Qu’est ce que le stress ? Lien entre stress et maladies Traits de personnalité et santé Les stratégies de coping Le soutien social La technique du CBSM (Cognitive Behavioral Stress Management) Qu’est ce que le stress ? On va avoir trois…",
    "themes": [
      "Santé",
      "Clinique"
    ],
    "keywords": [
      "CM02 — Stress & Maladies",
      "UE1 - CLINIQUE/CLINIQUE DE LA SANTE/CM02 - Stress & Maladies.docx",
      "CM — Clinique de la santé",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique de la santé",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/clinique-de-la-sante/cm02-stress-et-maladies.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-clinique-de-la-sante-cm02-stress-et-maladies"
  },
  {
    "id": "cours:psy-l2-s4-ue1-clinique-de-la-sante-cm03-exemples-de-therapie-en-psychologie-de-la-sante",
    "slug": "cm03-exemples-de-therapie-en-psychologie-de-la-sante.md",
    "title": "CM03 — Exemples de thérapie en psychologie de la santé",
    "module": "CM — Clinique de la santé",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 3,
    "description": "Exemples de thérapie en psychologie de la santé Les TCC La relaxation Le CBSM : Cognitive Behavioral Stress Management (gestion du stress basé sur les TCC) (Carver & Antoni) Les TCC Aujourd’hui, on prend l’aspect cognitif et plus juste stimulus + signal. C’est issu d’observations…",
    "themes": [
      "Santé",
      "Clinique"
    ],
    "keywords": [
      "CM03 — Exemples de thérapie en psychologie de la santé",
      "UE1 - CLINIQUE/CLINIQUE DE LA SANTE/CM03 - Exemples de thérapie en psychologie de la santé.docx",
      "CM — Clinique de la santé",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique de la santé",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/clinique-de-la-sante/cm03-exemples-de-therapie-en-psychologie-de-la-sante.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-clinique-de-la-sante-cm03-exemples-de-therapie-en-psychologie-de-la-sante"
  },
  {
    "id": "cours:psy-l2-s4-ue1-clinique-de-la-sante-cm04-06-la-psychologie-et-la-maladie-exemple-du-vih",
    "slug": "cm04-06-la-psychologie-et-la-maladie-exemple-du-vih.md",
    "title": "CM04-06 — La psychologie et la maladie (exemple du VIH)",
    "module": "CM — Clinique de la santé",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 4,
    "description": "La psychologie et la maladie (ex VIH) Le VIH et le SIDA : épidémiologie Le rôle de la psychologie dans l’étude du VIH : prévention du VIH Adaptation psychologique des patients atteints de maladies chroniques Le changement de valeurs Le VIH et le SIDA : épidémiologie VIH : Virus de…",
    "themes": [
      "Santé",
      "Clinique"
    ],
    "keywords": [
      "CM04-06 — La psychologie et la maladie (exemple du VIH)",
      "UE1 - CLINIQUE/CLINIQUE DE LA SANTE/CM04 06 - La psychologie et la maladie (exemple du VIH).docx",
      "CM — Clinique de la santé",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique de la santé",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/clinique-de-la-sante/cm04-06-la-psychologie-et-la-maladie-exemple-du-vih.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-clinique-de-la-sante-cm04-06-la-psychologie-et-la-maladie-exemple-du-vih"
  },
  {
    "id": "cours:psy-l2-s4-ue1-clinique-de-la-sante-cm05-qualite-de-vie",
    "slug": "cm05-qualite-de-vie.md",
    "title": "CM05 — Qualité de vie",
    "module": "CM — Clinique de la santé",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 5,
    "description": "Qualité de vie Qu’est ce donc que la qualité de vie ? Introduction L’OMS définit la qualité de vie comme : « La perception qu’a un individu de sa place dans l’existence, dans le contexte de la culture et du système de valeur dans lequel il vit, en relation avec ses objectifs, ses…",
    "themes": [
      "Santé",
      "Clinique"
    ],
    "keywords": [
      "CM05 — Qualité de vie",
      "UE1 - CLINIQUE/CLINIQUE DE LA SANTE/CM05 - Qualité de vie.docx",
      "CM — Clinique de la santé",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique de la santé",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/clinique-de-la-sante/cm05-qualite-de-vie.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-clinique-de-la-sante-cm05-qualite-de-vie"
  },
  {
    "id": "cours:psy-l2-s4-ue1-clinique-de-la-sante-cm06-07-les-determinants-de-l-adhesion",
    "slug": "cm06-07-les-determinants-de-l-adhesion.md",
    "title": "CM06-07 — Les déterminants de l’adhésion",
    "module": "CM — Clinique de la santé",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 6,
    "description": "Les déterminants de l’adhésion Comment définir l’adhésion Comment mesurer l’adhésion, des outils ? Les facteurs qui influencent l’adhésion Comment accompagner l’adhésion médicamenteuse ? Comment définir l’adhésion L’observance Qu’est ce que l’observance ? L’observance (=adhésion)…",
    "themes": [
      "Santé",
      "Clinique"
    ],
    "keywords": [
      "CM06-07 — Les déterminants de l’adhésion",
      "UE1 - CLINIQUE/CLINIQUE DE LA SANTE/CM06-07 - Les déterminants de l’adhésion.docx",
      "CM — Clinique de la santé",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique de la santé",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/clinique-de-la-sante/cm06-07-les-determinants-de-l-adhesion.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-clinique-de-la-sante-cm06-07-les-determinants-de-l-adhesion"
  },
  {
    "id": "cours:psy-l2-s4-ue1-clinique-de-la-sante-cm07-10-dialogue-autour-de-la-vaccination",
    "slug": "cm07-10-dialogue-autour-de-la-vaccination.md",
    "title": "CM07-10 — Dialogue autour de la vaccination",
    "module": "CM — Clinique de la santé",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 7,
    "description": "Dialogue autour de la vaccination : Comprendre les freins pour lever les hésitations Introduction De l’information à la décision De la décision au comportement Maintien et diffusion du comportement Conclusion Introduction L’HPV (papillomavirus humain) : Les types 16 & 18 sont…",
    "themes": [
      "Santé",
      "Clinique"
    ],
    "keywords": [
      "CM07-10 — Dialogue autour de la vaccination",
      "UE1 - CLINIQUE/CLINIQUE DE LA SANTE/CM07 10 - Dialogue autour de la vaccination.docx",
      "CM — Clinique de la santé",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique de la santé",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/clinique-de-la-sante/cm07-10-dialogue-autour-de-la-vaccination.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-clinique-de-la-sante-cm07-10-dialogue-autour-de-la-vaccination"
  },
  {
    "id": "cours:psy-l2-s4-ue1-clinique-de-la-sante-cm08-09-le-comportement-alimentaire",
    "slug": "cm08-09-le-comportement-alimentaire.md",
    "title": "CM08-09 — Le comportement alimentaire",
    "module": "CM — Clinique de la santé",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 8,
    "description": "Les comportements alimentaires Ce cours est issu de l’ouvrage d’Ogden (2014) Introduction Modèles du comportement alimentaire Rôle des préoccupations liées au poids Introduction Alimentation saine On se retrouve avec des notions qu’on nous rabâche depuis notre naissance. Une…",
    "themes": [
      "Santé",
      "Clinique"
    ],
    "keywords": [
      "CM08-09 — Le comportement alimentaire",
      "UE1 - CLINIQUE/CLINIQUE DE LA SANTE/CM08-09 - Le comportement alimentaire.docx",
      "CM — Clinique de la santé",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique de la santé",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/clinique-de-la-sante/cm08-09-le-comportement-alimentaire.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-clinique-de-la-sante-cm08-09-le-comportement-alimentaire"
  },
  {
    "id": "cours:psy-l2-s4-ue1-clinique-de-la-sante-cm11-psychologie-de-la-sante",
    "slug": "cm11-psychologie-de-la-sante.md",
    "title": "CM11 — Psychologie de la santé",
    "module": "CM — Clinique de la santé",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 9,
    "description": "Psychologie de la santé : La douleur Une personne sur 5 en Europe souffre de douleur chronique. Il y a un fort lien avec la dépression. En France, environ 12 000 000 de personnes souffrent de douleurs chroniques et 2.6 millions de personnes souffrent de douleur neuropathique. Les…",
    "themes": [
      "Santé",
      "Clinique"
    ],
    "keywords": [
      "CM11 — Psychologie de la santé",
      "UE1 - CLINIQUE/CLINIQUE DE LA SANTE/CM11 - Psychologie de la santé.docx",
      "CM — Clinique de la santé",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique de la santé",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/clinique-de-la-sante/cm11-psychologie-de-la-sante.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-clinique-de-la-sante-cm11-psychologie-de-la-sante"
  },
  {
    "id": "cours:psy-l2-s4-ue1-clinique-de-la-sante-cm12-les-modeles-en-psychologie-de-la-sante",
    "slug": "cm12-les-modeles-en-psychologie-de-la-sante.md",
    "title": "CM12 — Les modèles en psychologie de la santé",
    "module": "CM — Clinique de la santé",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 10,
    "description": "Les modèles en psychologie de la santé Le modèle bio psycho social Les théories naïves de la santé Prédire le comportement de santé (LOC, modèle trans théorique) Modèles cognitif (HBM) Modèle socio cognitif (TPB, HAPA) Problèmes posés par ces théories (prédire le comportement =…",
    "themes": [
      "Santé",
      "Clinique"
    ],
    "keywords": [
      "CM12 — Les modèles en psychologie de la santé",
      "UE1 - CLINIQUE/CLINIQUE DE LA SANTE/CM12 - Les modèles en psychologie de la santé.docx",
      "CM — Clinique de la santé",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique de la santé",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/clinique-de-la-sante/cm12-les-modeles-en-psychologie-de-la-sante.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-clinique-de-la-sante-cm12-les-modeles-en-psychologie-de-la-sante"
  },
  {
    "id": "cours:psy-l2-s4-ue1-methode-clinique-cm01-code-de-deontologie",
    "slug": "cm01-code-de-deontologie.md",
    "title": "CM01 — Code de déontologie",
    "module": "CM — Méthode clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 11,
    "description": "Code de déontologie Le code de déontologie a établi en 1996 avec différente association : SDP AEPU : Association des Enseignants Chercheurs ANOP : Association Nationale des Organisations de Psychologues GIRéDéP : Groupe Inter organisationnel pour la Réglementation de la Déontologie…",
    "themes": [
      "Méthode clinique",
      "Entretien",
      "Observation"
    ],
    "keywords": [
      "CM01 — Code de déontologie",
      "UE1 - CLINIQUE/METHODE CLINIQUE/CM01 - Code de déontologie.docx",
      "CM — Méthode clinique",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Méthode clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/methode-clinique/cm01-code-de-deontologie.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-methode-clinique-cm01-code-de-deontologie"
  },
  {
    "id": "cours:psy-l2-s4-ue1-methode-clinique-cm02-methode-clinique",
    "slug": "cm02-methode-clinique.md",
    "title": "CM02 — Méthode clinique",
    "module": "CM — Méthode clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 12,
    "description": "Méthode clinique Qu’est ce qu’on entend par méthode clinique ? « L’étude approfondie des cas individuels ou l’étude de la conduite humaine individuelle et de ses conditions (hérédité, maturation, conditions physiologiques et pathologiques, histoire de vie), en un mot, l’étude de la…",
    "themes": [
      "Méthode clinique",
      "Entretien",
      "Observation"
    ],
    "keywords": [
      "CM02 — Méthode clinique",
      "UE1 - CLINIQUE/METHODE CLINIQUE/CM02 - Méthode clinique.docx",
      "CM — Méthode clinique",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Méthode clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/methode-clinique/cm02-methode-clinique.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-methode-clinique-cm02-methode-clinique"
  },
  {
    "id": "cours:psy-l2-s4-ue1-methode-clinique-cm02-04-l-observation",
    "slug": "cm02-04-l-observation.md",
    "title": "CM02-04 — L observation",
    "module": "CM — Méthode clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 13,
    "description": "L’observation Définition Quand on y pense, l’observation est le fondement de la connaissance. Elle est présente dans toutes les observations rencontrées. « Processus incluant l’attention volontaire et l’intelligence orientées vers un objectif, vers un objet, pour recueillir des…",
    "themes": [
      "Méthode clinique",
      "Entretien",
      "Observation"
    ],
    "keywords": [
      "CM02-04 — L observation",
      "UE1 - CLINIQUE/METHODE CLINIQUE/CM02-04 - L observation.docx",
      "CM — Méthode clinique",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Méthode clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/methode-clinique/cm02-04-l-observation.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-methode-clinique-cm02-04-l-observation"
  },
  {
    "id": "cours:psy-l2-s4-ue1-methode-clinique-cm04-06-l-entretien-clinique",
    "slug": "cm04-06-l-entretien-clinique.md",
    "title": "CM04-06 — L entretien clinique",
    "module": "CM — Méthode clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 14,
    "description": "L’entretien clinique Définition On pourrait dire que l’entretien est l’action d’échanger des paroles avec une ou plusieurs personnes. L’échange suppose qu’il y est une transmission symbolique (prend une valeur subjective, la personne qui parle va mettre en mots des objets & situation…",
    "themes": [
      "Méthode clinique",
      "Entretien",
      "Observation"
    ],
    "keywords": [
      "CM04-06 — L entretien clinique",
      "UE1 - CLINIQUE/METHODE CLINIQUE/CM04-06 - L entretien clinique.docx",
      "CM — Méthode clinique",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Méthode clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/methode-clinique/cm04-06-l-entretien-clinique.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-methode-clinique-cm04-06-l-entretien-clinique"
  },
  {
    "id": "cours:psy-l2-s4-ue1-methode-clinique-cm06-les-tests-et-les-echelles",
    "slug": "cm06-les-tests-et-les-echelles.md",
    "title": "CM06 — Les tests et les échelles",
    "module": "CM — Méthode clinique",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 15,
    "description": "Les tests et les échelles On va avoir des outils d’évaluation qui sont standardisé. Tout est standardisé, on va faire toujours la même chose avec les mêmes sujets. On va parler de psychométrie qui désigne la discipline qui évalue les caractéristiques psychiques grâce à des…",
    "themes": [
      "Méthode clinique",
      "Entretien",
      "Observation"
    ],
    "keywords": [
      "CM06 — Les tests et les échelles",
      "UE1 - CLINIQUE/METHODE CLINIQUE/CM06 - Les tests et les échelles.docx",
      "CM — Méthode clinique",
      "UE1 — Clinique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE1 — Clinique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Méthode clinique",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue1/methode-clinique/cm06-les-tests-et-les-echelles.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue1-methode-clinique-cm06-les-tests-et-les-echelles"
  },
  {
    "id": "cours:psy-l2-s4-ue2-psychologie-sociale-cm01-03-introduction-et-principes-de-bases",
    "slug": "cm01-03-introduction-et-principes-de-bases.md",
    "title": "CM01-03 — Introduction et principes de bases",
    "module": "CM — Psychologie sociale",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 16,
    "description": "Introduction et principe de bases Bibliographie : 5 articles Et si le bonheur vous tombait dessus, Daniel Todd Gilbert Croyance & méthodes scientifiques La conscience, la non conscience et l’inconscience Conclusion Les individus ne sont que très rarement conscients des facteurs…",
    "themes": [
      "Psychologie sociale"
    ],
    "keywords": [
      "CM01-03 — Introduction et principes de bases",
      "UE2 - SOCIALE/CM01-03 - Introduction et principes de bases.docx",
      "CM — Psychologie sociale",
      "UE2 — Psychologie sociale",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE2 — Psychologie sociale",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie sociale",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue2/psychologie-sociale/cm01-03-introduction-et-principes-de-bases.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue2-psychologie-sociale-cm01-03-introduction-et-principes-de-bases"
  },
  {
    "id": "cours:psy-l2-s4-ue2-psychologie-sociale-cm03-09-perception-de-soi-et-des-autres",
    "slug": "cm03-09-perception-de-soi-et-des-autres.md",
    "title": "CM03-09 — Perception de soi et des autres",
    "module": "CM — Psychologie sociale",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 17,
    "description": "Perception de soi et des autres Formation d’impression : percevoir autrui Rôle de l’accessibilité Schéma et Catégorisation Théories implicites de la Personnalité (TIP) Formation d’impression Connaissance de soi La nature du soi Les sources de connaissances de soi On va chercher…",
    "themes": [
      "Psychologie sociale"
    ],
    "keywords": [
      "CM03-09 — Perception de soi et des autres",
      "UE2 - SOCIALE/CM03-09 - Perception de soi et des autres.docx",
      "CM — Psychologie sociale",
      "UE2 — Psychologie sociale",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE2 — Psychologie sociale",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie sociale",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue2/psychologie-sociale/cm03-09-perception-de-soi-et-des-autres.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue2-psychologie-sociale-cm03-09-perception-de-soi-et-des-autres"
  },
  {
    "id": "cours:psy-l2-s4-ue2-psychologie-sociale-cm10-relations-interpersonnelles",
    "slug": "cm10-relations-interpersonnelles.md",
    "title": "CM10 — Relations interpersonnelles",
    "module": "CM — Psychologie sociale",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 18,
    "description": "Relations interpersonnelles Attraction interpersonnelle Facteurs favorisant l’attraction interpersonnelle Proximité C’est l’idée que la simple proximité avec autrui peut emmener d’être proche de quelqu’un plutôt que quelqu’un d’autre. Le fait d’être plus proche avec les autres…",
    "themes": [
      "Psychologie sociale"
    ],
    "keywords": [
      "CM10 — Relations interpersonnelles",
      "UE2 - SOCIALE/CM10 - Relations interpersonnelles.docx",
      "CM — Psychologie sociale",
      "UE2 — Psychologie sociale",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE2 — Psychologie sociale",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie sociale",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue2/psychologie-sociale/cm10-relations-interpersonnelles.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue2-psychologie-sociale-cm10-relations-interpersonnelles"
  },
  {
    "id": "cours:psy-l2-s4-ue2-psychologie-sociale-cm10-11-relations-interpersonnelles",
    "slug": "cm10-11-relations-interpersonnelles.md",
    "title": "CM10-11 — Relations interpersonnelles",
    "module": "CM — Psychologie sociale",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 19,
    "description": "Relations interpersonnelles Attraction interpersonnelle Facteurs favorisant l’attraction interpersonnelle Proximité C’est l’idée que la simple proximité avec autrui peut emmener d’être proche de quelqu’un plutôt que quelqu’un d’autre. Le fait d’être plus proche avec les autres…",
    "themes": [
      "Psychologie sociale"
    ],
    "keywords": [
      "CM10-11 — Relations interpersonnelles",
      "UE2 - SOCIALE/CM10-11 - Relations interpersonnelles.docx",
      "CM — Psychologie sociale",
      "UE2 — Psychologie sociale",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE2 — Psychologie sociale",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie sociale",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue2/psychologie-sociale/cm10-11-relations-interpersonnelles.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue2-psychologie-sociale-cm10-11-relations-interpersonnelles"
  },
  {
    "id": "cours:psy-l2-s4-ue2-psychologie-sociale-cm12-influence-sociale",
    "slug": "cm12-influence-sociale.md",
    "title": "CM12 — Influence sociale",
    "module": "CM — Psychologie sociale",
    "courseTheme": "sociale",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 20,
    "description": "Influence sociale Psychologie sociale, David G. Myers, Luc Lemarche « Les phénomènes d’influence concernent les processus par lesquels les individus et les groupes façonnent, maintiennent, diffusent et modifient leurs modes de pensée et d’action » Mugny Dans le champ de la…",
    "themes": [
      "Psychologie sociale"
    ],
    "keywords": [
      "CM12 — Influence sociale",
      "UE2 - SOCIALE/CM12 - Influence sociale.docx",
      "CM — Psychologie sociale",
      "UE2 — Psychologie sociale",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE2 — Psychologie sociale",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie sociale",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue2/psychologie-sociale/cm12-influence-sociale.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue2-psychologie-sociale-cm12-influence-sociale"
  },
  {
    "id": "cours:psy-l2-s4-ue3-psychologie-differentielle-cm01-1-psychologie-differentielle-et-psychometrie",
    "slug": "cm01-1-psychologie-differentielle-et-psychometrie.md",
    "title": "CM01-1 — Psychologie différentielle & Psychométrie",
    "module": "CM — Psychologie différentielle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 21,
    "description": "Psychologie différentielle & Psychométrie L’objectif de cette psychologie est de décrire & expliquer au moyen de méthodes objectives les différences psychologiques des individus (Huteau, 1995). Ces différences peuvent être observées pour un même individu dans des situations ou à des…",
    "themes": [
      "Psychologie différentielle",
      "Psychométrie"
    ],
    "keywords": [
      "CM01-1 — Psychologie différentielle & Psychométrie",
      "UE3 - DIFFERENTIELLE/CM01.1 - Psychologie différentielle & Psychométrie.docx",
      "CM — Psychologie différentielle",
      "UE3 — Psychologie différentielle",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE3 — Psychologie différentielle",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie différentielle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue3/psychologie-differentielle/cm01-1-psychologie-differentielle-et-psychometrie.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue3-psychologie-differentielle-cm01-1-psychologie-differentielle-et-psychometrie"
  },
  {
    "id": "cours:psy-l2-s4-ue3-psychologie-differentielle-cm01-2-naissance-et-definition-de-la-psychologie-differentielle",
    "slug": "cm01-2-naissance-et-definition-de-la-psychologie-differentielle.md",
    "title": "CM01-2 — Naissance et définition de la Psychologie différentielle",
    "module": "CM — Psychologie différentielle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 22,
    "description": "Naissance et définition de la Psychologie différentielle Le constat des différences Innéisme et empirisme La révolution Darwinienne L’école anglaise de F.Galton (1822 1911) Psychologie expérimentale, l’erreur de la variabilité Test de Cattell et résultats académiques Dans le même…",
    "themes": [
      "Psychologie différentielle",
      "Psychométrie"
    ],
    "keywords": [
      "CM01-2 — Naissance et définition de la Psychologie différentielle",
      "UE3 - DIFFERENTIELLE/CM01.2 - Naissance et définition de la Psychologie différentielle.docx",
      "CM — Psychologie différentielle",
      "UE3 — Psychologie différentielle",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE3 — Psychologie différentielle",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie différentielle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue3/psychologie-differentielle/cm01-2-naissance-et-definition-de-la-psychologie-differentielle.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue3-psychologie-differentielle-cm01-2-naissance-et-definition-de-la-psychologie-differentielle"
  },
  {
    "id": "cours:psy-l2-s4-ue3-psychologie-differentielle-cm02-05-la-methode-des-tests",
    "slug": "cm02-05-la-methode-des-tests.md",
    "title": "CM02-05 — La méthode des tests",
    "module": "CM — Psychologie différentielle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 23,
    "description": "Psychométrie ? Comment évaluer le psychologique : la méthode des tests Différents types de tests Qualité métriques de test La construction d’un test : les grandes étapes Le choix initial des items La standardisation L’analyse des réponses aux items initiaux La sensibilité et…",
    "themes": [
      "Psychologie différentielle",
      "Psychométrie"
    ],
    "keywords": [
      "CM02-05 — La méthode des tests",
      "UE3 - DIFFERENTIELLE/CM02-05 - La méthode des tests.docx",
      "CM — Psychologie différentielle",
      "UE3 — Psychologie différentielle",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE3 — Psychologie différentielle",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie différentielle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue3/psychologie-differentielle/cm02-05-la-methode-des-tests.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue3-psychologie-differentielle-cm02-05-la-methode-des-tests"
  },
  {
    "id": "cours:psy-l2-s4-ue3-psychologie-differentielle-cm05-08-psychologie-differentielle-et-intelligence",
    "slug": "cm05-08-psychologie-differentielle-et-intelligence.md",
    "title": "CM05-08 — Psychologie différentielle et intelligence",
    "module": "CM — Psychologie différentielle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 24,
    "description": "Psychologie différentielle et intelligence Qu’est ce que l’intelligence (1921) ? Les dimensions de l’intelligence Aspects déontologiques Autres mesures de l’intelligence Qu’est ce que l’intelligence (1921) ? Dearborn dit que c’est la capacité à apprendre ou à profiter de…",
    "themes": [
      "Psychologie différentielle",
      "Psychométrie"
    ],
    "keywords": [
      "CM05-08 — Psychologie différentielle et intelligence",
      "UE3 - DIFFERENTIELLE/CM05-08 - Psychologie différentielle et intelligence.docx",
      "CM — Psychologie différentielle",
      "UE3 — Psychologie différentielle",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE3 — Psychologie différentielle",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie différentielle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue3/psychologie-differentielle/cm05-08-psychologie-differentielle-et-intelligence.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue3-psychologie-differentielle-cm05-08-psychologie-differentielle-et-intelligence"
  },
  {
    "id": "cours:psy-l2-s4-ue3-psychologie-differentielle-cm09-10-psychologie-differentielle-et-personnalite",
    "slug": "cm09-10-psychologie-differentielle-et-personnalite.md",
    "title": "CM09-10 — Psychologie différentielle et personnalité",
    "module": "CM — Psychologie différentielle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 25,
    "description": "Psychologie différentielle et personnalité Le thème de la personnalité est très utilisé dans nos sociétés : horoscope, numérologie, physiognomonie, graphologie et autre Effet Barnum : on peut penser que cela nous ressemble car vague et contradictoire Dans le sens commun, on veut…",
    "themes": [
      "Psychologie différentielle",
      "Psychométrie"
    ],
    "keywords": [
      "CM09-10 — Psychologie différentielle et personnalité",
      "UE3 - DIFFERENTIELLE/CM09-10 - Psychologie différentielle et personnalité.docx",
      "CM — Psychologie différentielle",
      "UE3 — Psychologie différentielle",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE3 — Psychologie différentielle",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie différentielle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue3/psychologie-differentielle/cm09-10-psychologie-differentielle-et-personnalite.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue3-psychologie-differentielle-cm09-10-psychologie-differentielle-et-personnalite"
  },
  {
    "id": "cours:psy-l2-s4-ue3-psychologie-differentielle-cm10-11-les-styles-cognitifs",
    "slug": "cm10-11-les-styles-cognitifs.md",
    "title": "CM10-11 — Les styles cognitifs",
    "module": "CM — Psychologie différentielle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 26,
    "description": "Les styles cognitifs On a un phénomène de variabilité interindividuelle relativement général et stable dans la forme de l’activité cognitive. Les styles cognitifs sont des modes de fonctionnement habituels du sujet, ceux qu’il tend à utiliser préférentiellement lorsque les situations…",
    "themes": [
      "Psychologie différentielle",
      "Psychométrie"
    ],
    "keywords": [
      "CM10-11 — Les styles cognitifs",
      "UE3 - DIFFERENTIELLE/CM10-11 - Les styles cognitifs.docx",
      "CM — Psychologie différentielle",
      "UE3 — Psychologie différentielle",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE3 — Psychologie différentielle",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie différentielle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue3/psychologie-differentielle/cm10-11-les-styles-cognitifs.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue3-psychologie-differentielle-cm10-11-les-styles-cognitifs"
  },
  {
    "id": "cours:psy-l2-s4-ue3-psychologie-differentielle-cm11-origine-des-differences-individuelles",
    "slug": "cm11-origine-des-differences-individuelles.md",
    "title": "CM11 — Origine des différences individuelles",
    "module": "CM — Psychologie différentielle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 27,
    "description": "Origine des différences individuelles Génétique et comportement On va avoir une structure donnée selon la génétique. Une structure génétique se développe, va former des embryons, dans un milieu particulier… Dans ce milieu, on va avoir des facteurs qui peuvent affecter les facteurs…",
    "themes": [
      "Psychologie différentielle",
      "Psychométrie"
    ],
    "keywords": [
      "CM11 — Origine des différences individuelles",
      "UE3 - DIFFERENTIELLE/CM11 - Origine des différences individuelles.docx",
      "CM — Psychologie différentielle",
      "UE3 — Psychologie différentielle",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE3 — Psychologie différentielle",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie différentielle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue3/psychologie-differentielle/cm11-origine-des-differences-individuelles.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue3-psychologie-differentielle-cm11-origine-des-differences-individuelles"
  },
  {
    "id": "cours:psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm01-anatomie-fonctionnelle-du-systeme-nerveux",
    "slug": "cm01-anatomie-fonctionnelle-du-systeme-nerveux.md",
    "title": "CM01 — Anatomie fonctionnelle du système nerveux",
    "module": "CM — Neuroanatomie fonctionnelle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 28,
    "description": "Introduction Le système nerveux La neuroanatomie fonctionnel est l’étude de la structure et de la forme des parties du système nerveux (=anatomie) et l’étude de la fonction des parties du système nerveux (=fonctionnelle). La psychologie n’est pas quelque chose de désincarner.…",
    "themes": [
      "Neuroanatomie",
      "Neurosciences"
    ],
    "keywords": [
      "CM01 — Anatomie fonctionnelle du système nerveux",
      "UE5 - NEUROSCIENCES/Neuroanatomie fonctionnel/CM01 - Anatomie fonctionnelle du système nerveux.docx",
      "CM — Neuroanatomie fonctionnelle",
      "UE5 — Neurosciences",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE5 — Neurosciences",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Neuroanatomie fonctionnelle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue5/neuroanatomie-fonctionnelle/cm01-anatomie-fonctionnelle-du-systeme-nerveux.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm01-anatomie-fonctionnelle-du-systeme-nerveux"
  },
  {
    "id": "cours:psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm02-developpement-du-systeme-nerveux",
    "slug": "cm02-developpement-du-systeme-nerveux.md",
    "title": "CM02 — Développement du système nerveux",
    "module": "CM — Neuroanatomie fonctionnelle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 29,
    "description": "Anatomie fonctionnelle du système nerveux Développement du système nerveux Le début se fait avec l’ovulation. Comment le SN a sa forme et sa fonction ? Genèse du SNC & SNP L’ontogenèse fait référence au développement de l’organisme de sa conception jusqu’à l’état mature (et mort).…",
    "themes": [
      "Neuroanatomie",
      "Neurosciences"
    ],
    "keywords": [
      "CM02 — Développement du système nerveux",
      "UE5 - NEUROSCIENCES/Neuroanatomie fonctionnel/CM02 - Développement du système nerveux.docx",
      "CM — Neuroanatomie fonctionnelle",
      "UE5 — Neurosciences",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE5 — Neurosciences",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Neuroanatomie fonctionnelle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue5/neuroanatomie-fonctionnelle/cm02-developpement-du-systeme-nerveux.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm02-developpement-du-systeme-nerveux"
  },
  {
    "id": "cours:psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm04-le-tronc-cerebral",
    "slug": "cm04-le-tronc-cerebral.md",
    "title": "CM04 — le tronc cérébral",
    "module": "CM — Neuroanatomie fonctionnelle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 30,
    "description": "Le tronc cérébral Généralité Le tronc cérébral fait partie de l’encéphale fait partie de la partie inférieure de la boite crânienne (dans le diencéphale). Il est dans la continuité de la moelle épinière et est devant le cervelet. Il est devant le cervelet avec qui il est relié via…",
    "themes": [
      "Neuroanatomie",
      "Neurosciences"
    ],
    "keywords": [
      "CM04 — le tronc cérébral",
      "UE5 - NEUROSCIENCES/Neuroanatomie fonctionnel/CM04 - le tronc cérébral.docx",
      "CM — Neuroanatomie fonctionnelle",
      "UE5 — Neurosciences",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE5 — Neurosciences",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Neuroanatomie fonctionnelle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue5/neuroanatomie-fonctionnelle/cm04-le-tronc-cerebral.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm04-le-tronc-cerebral"
  },
  {
    "id": "cours:psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm05-les-nerfs-craniens",
    "slug": "cm05-les-nerfs-craniens.md",
    "title": "CM05 — Les nerfs crâniens",
    "module": "CM — Neuroanatomie fonctionnelle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 31,
    "description": "Les nerfs crâniens Il existe 12 paires noté de I à XII. Ils vont soit avoir une fonction motrice (énerver les muscles striés) soit une fonction sensorielle (énervation des organes de sens) soit une fonction somesthésique, fonction végétative (énervation des muscles lisses et des…",
    "themes": [
      "Neuroanatomie",
      "Neurosciences"
    ],
    "keywords": [
      "CM05 — Les nerfs crâniens",
      "UE5 - NEUROSCIENCES/Neuroanatomie fonctionnel/CM05 - Les nerfs crâniens.docx",
      "CM — Neuroanatomie fonctionnelle",
      "UE5 — Neurosciences",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE5 — Neurosciences",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Neuroanatomie fonctionnelle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue5/neuroanatomie-fonctionnelle/cm05-les-nerfs-craniens.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm05-les-nerfs-craniens"
  },
  {
    "id": "cours:psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm06-anatomie-fonctionnelle-du-systeme-nerveux",
    "slug": "cm06-anatomie-fonctionnelle-du-systeme-nerveux.md",
    "title": "CM06 — Anatomie fonctionnelle du système nerveux",
    "module": "CM — Neuroanatomie fonctionnelle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 32,
    "description": "Anatomie fonctionnelle du système nerveux Généralités Elle va avoir une fonction de correction de la fonction motrice. C’est une régulation du mouvement volontaire via l’ajustement de l’équilibre du tonus musculaire et par la coordination temporospatial du mouvement. Le cervelet est…",
    "themes": [
      "Neuroanatomie",
      "Neurosciences"
    ],
    "keywords": [
      "CM06 — Anatomie fonctionnelle du système nerveux",
      "UE5 - NEUROSCIENCES/Neuroanatomie fonctionnel/CM06 - Anatomie fonctionnelle du système nerveux.docx",
      "CM — Neuroanatomie fonctionnelle",
      "UE5 — Neurosciences",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE5 — Neurosciences",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Neuroanatomie fonctionnelle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue5/neuroanatomie-fonctionnelle/cm06-anatomie-fonctionnelle-du-systeme-nerveux.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm06-anatomie-fonctionnelle-du-systeme-nerveux"
  },
  {
    "id": "cours:psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm07-le-diencephale",
    "slug": "cm07-le-diencephale.md",
    "title": "CM07 — Le diencéphale",
    "module": "CM — Neuroanatomie fonctionnelle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 33,
    "description": "Le diencéphale Généralité Il est présent dans la majeure partie du cerveau. Il est présent pour le relais de l’information entrante qui provient de la moelle épinière mais uassi de l’information qui provient du cerveau. Il est aussi impliqué dans la régulation du cycle veille /…",
    "themes": [
      "Neuroanatomie",
      "Neurosciences"
    ],
    "keywords": [
      "CM07 — Le diencéphale",
      "UE5 - NEUROSCIENCES/Neuroanatomie fonctionnel/CM07 - Le diencéphale.docx",
      "CM — Neuroanatomie fonctionnelle",
      "UE5 — Neurosciences",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE5 — Neurosciences",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Neuroanatomie fonctionnelle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue5/neuroanatomie-fonctionnelle/cm07-le-diencephale.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm07-le-diencephale"
  },
  {
    "id": "cours:psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm09-le-cerveau",
    "slug": "cm09-le-cerveau.md",
    "title": "CM09 — Le cerveau",
    "module": "CM — Neuroanatomie fonctionnelle",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 34,
    "description": "Le cerveau Généralités & rappels Le cerveau est issu du prosencéphale issue lui même du télencéphale. Le prosencéphale donne aussi le diencéphale. On peut voir qu’il existe 4 lobes (ci dessus). On peut considérer qu’il y a un 5° lobe qui est le lobe insulaire. Il y a 4 ventricules…",
    "themes": [
      "Neuroanatomie",
      "Neurosciences"
    ],
    "keywords": [
      "CM09 — Le cerveau",
      "UE5 - NEUROSCIENCES/Neuroanatomie fonctionnel/CM09 - Le cerveau.docx",
      "CM — Neuroanatomie fonctionnelle",
      "UE5 — Neurosciences",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE5 — Neurosciences",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Neuroanatomie fonctionnelle",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue5/neuroanatomie-fonctionnelle/cm09-le-cerveau.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue5-neuroanatomie-fonctionnelle-cm09-le-cerveau"
  },
  {
    "id": "cours:psy-l2-s4-ue5-neurosciences-fondamentales-cm01-introduction-aux-neurosciences-role-principal-et-subdivision-du-systeme-nerveux",
    "slug": "cm01-introduction-aux-neurosciences-role-principal-et-subdivision-du-systeme-nerveux.md",
    "title": "CM01 — Introduction aux neurosciences — Rôle principal & subdivision du système nerveux",
    "module": "CM — Neurosciences fondamentales",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 35,
    "description": "Introduction aux neurosciences Rôle principal & subdivision du système nerveux Une des premières fonctions du système nerveux est de recueillir / percevoir l’information de l’environnement externes (=autour de nous, informations visuelles / auditives) / internes à l’organisme. On va…",
    "themes": [
      "Neurosciences",
      "Système nerveux"
    ],
    "keywords": [
      "CM01 — Introduction aux neurosciences — Rôle principal & subdivision du système nerveux",
      "UE5 - NEUROSCIENCES/Neuroscience fondamentale/CM01 - Introduction aux neurosciences - Rôle principal & subdivision du système nerveux.docx",
      "CM — Neurosciences fondamentales",
      "UE5 — Neurosciences",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE5 — Neurosciences",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Neurosciences fondamentales",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue5/neurosciences-fondamentales/cm01-introduction-aux-neurosciences-role-principal-et-subdivision-du-systeme-nerveux.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue5-neurosciences-fondamentales-cm01-introduction-aux-neurosciences-role-principal-et-subdivision-du-systeme-nerveux"
  },
  {
    "id": "cours:psy-l2-s4-ue5-neurosciences-fondamentales-cm01-02-niveaux-d-analyse-du-systeme-nerveux",
    "slug": "cm01-02-niveaux-d-analyse-du-systeme-nerveux.md",
    "title": "CM01-02 — Niveaux d’analyse du système nerveux",
    "module": "CM — Neurosciences fondamentales",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 36,
    "description": "Niveaux d’analyse du système nerveux Neurosciences cognitives & comportementales Neuroscience intégrées Neurobiologie cellulaire Neurobiologie moléculaire Neurosciences cognitives & comportementales On va ici étudier dans son ensemble le système. On va avoir dans le lot des…",
    "themes": [
      "Neurosciences",
      "Système nerveux"
    ],
    "keywords": [
      "CM01-02 — Niveaux d’analyse du système nerveux",
      "UE5 - NEUROSCIENCES/Neuroscience fondamentale/CM01-02 - Niveaux d’analyse du système nerveux.docx",
      "CM — Neurosciences fondamentales",
      "UE5 — Neurosciences",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE5 — Neurosciences",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Neurosciences fondamentales",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue5/neurosciences-fondamentales/cm01-02-niveaux-d-analyse-du-systeme-nerveux.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue5-neurosciences-fondamentales-cm01-02-niveaux-d-analyse-du-systeme-nerveux"
  },
  {
    "id": "cours:psy-l2-s4-ue5-neurosciences-fondamentales-cm02-06-cellules-du-systeme-nerveux",
    "slug": "cm02-06-cellules-du-systeme-nerveux.md",
    "title": "CM02-06 — Cellules du système nerveux",
    "module": "CM — Neurosciences fondamentales",
    "courseTheme": "cognition",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 37,
    "description": "Cellules du système nerveux Les neurones Rôle Structure et polarisation Classification Les cellules gliales Les autres cellules Les neurones Rôle Elles vont avoir le rôle de réception, d’intégration et de transmission à distance de l’information sous forme de signal électrique. Au…",
    "themes": [
      "Neurosciences",
      "Système nerveux"
    ],
    "keywords": [
      "CM02-06 — Cellules du système nerveux",
      "UE5 - NEUROSCIENCES/Neuroscience fondamentale/CM02-06 - Cellules du système nerveux.docx",
      "CM — Neurosciences fondamentales",
      "UE5 — Neurosciences",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE5 — Neurosciences",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Neurosciences fondamentales",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue5/neurosciences-fondamentales/cm02-06-cellules-du-systeme-nerveux.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue5-neurosciences-fondamentales-cm02-06-cellules-du-systeme-nerveux"
  },
  {
    "id": "cours:psy-l2-s4-ue6-clinique-des-emotions-cm01-les-emotions-entre-rejet-et-fascination",
    "slug": "cm01-les-emotions-entre-rejet-et-fascination.md",
    "title": "CM01 — Les émotions — entre rejet et fascination",
    "module": "CM — Clinique des émotions",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 38,
    "description": "Les émotions entre rejet et fascination L’intérêt sur les émotions a été très variable au cours du temps. Approche philosophique, psychopathologique & psychologie On va avoir une approche différence selon le temps. A l’époque de Platon, on différenciait l’animal de l’homme avec la…",
    "themes": [
      "Émotions",
      "Clinique"
    ],
    "keywords": [
      "CM01 — Les émotions — entre rejet et fascination",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/CLINIQUE DES EMOTIONS/CM01 - Les émotions - entre rejet et fascination.docx",
      "CM — Clinique des émotions",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique des émotions",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/clinique-des-emotions/cm01-les-emotions-entre-rejet-et-fascination.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-clinique-des-emotions-cm01-les-emotions-entre-rejet-et-fascination"
  },
  {
    "id": "cours:psy-l2-s4-ue6-clinique-des-emotions-cm01-04-evaluation-et-signification-emotionnelle",
    "slug": "cm01-04-evaluation-et-signification-emotionnelle.md",
    "title": "CM01-04 — Evaluation et signification émotionnelle",
    "module": "CM — Clinique des émotions",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 39,
    "description": "Evaluation Et signification émotionnelle Introduction On va avoir différente théorie de l’évaluation (Smith & Kirby 2001, Roseman 1991). Certaines émotions sont acquises et d’autres sont innées. On va essayer de voir l’évaluation et les niveaux de traitements des émotions (de l’innée…",
    "themes": [
      "Émotions",
      "Clinique"
    ],
    "keywords": [
      "CM01-04 — Evaluation et signification émotionnelle",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/CLINIQUE DES EMOTIONS/CM01-04 - Evaluation et signification émotionnelle.docx",
      "CM — Clinique des émotions",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique des émotions",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/clinique-des-emotions/cm01-04-evaluation-et-signification-emotionnelle.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-clinique-des-emotions-cm01-04-evaluation-et-signification-emotionnelle"
  },
  {
    "id": "cours:psy-l2-s4-ue6-clinique-des-emotions-cm05-06-regulation-des-emotions",
    "slug": "cm05-06-regulation-des-emotions.md",
    "title": "CM05-06 — Régulation des émotions",
    "module": "CM — Clinique des émotions",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 40,
    "description": "Régulation des émotions Historique du concept de régulation émotionnelle On va avoir des mécanismes de défenses quand on est submergé par certains types d’émotions. L’intérêt de la régulation émotionnelle vient en grande partie des mécanismes de défenses dans la perceptive…",
    "themes": [
      "Émotions",
      "Clinique"
    ],
    "keywords": [
      "CM05-06 — Régulation des émotions",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/CLINIQUE DES EMOTIONS/CM05-06 - Régulation des émotions.docx",
      "CM — Clinique des émotions",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique des émotions",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/clinique-des-emotions/cm05-06-regulation-des-emotions.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-clinique-des-emotions-cm05-06-regulation-des-emotions"
  },
  {
    "id": "cours:psy-l2-s4-ue6-clinique-des-emotions-cm07-emotions-et-regulation-des-emotions",
    "slug": "cm07-emotions-et-regulation-des-emotions.md",
    "title": "CM07 — Emotions et régulation des émotions",
    "module": "CM — Clinique des émotions",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 41,
    "description": "Emotions et régulation des émotions, une heuristique de compréhension des troubles et difficultés psychologiques On constate de manière générale une sous activation. Par exemple avec l’émoussement affectif dans le stress post traumatique, l’émotion positive sous activée dans les…",
    "themes": [
      "Émotions",
      "Clinique"
    ],
    "keywords": [
      "CM07 — Emotions et régulation des émotions",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/CLINIQUE DES EMOTIONS/CM07 - Emotions et régulation des émotions.docx",
      "CM — Clinique des émotions",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique des émotions",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/clinique-des-emotions/cm07-emotions-et-regulation-des-emotions.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-clinique-des-emotions-cm07-emotions-et-regulation-des-emotions"
  },
  {
    "id": "cours:psy-l2-s4-ue6-clinique-des-emotions-cm08-psychopathologie-des-emotions",
    "slug": "cm08-psychopathologie-des-emotions.md",
    "title": "CM08 — Psychopathologie des émotions",
    "module": "CM — Clinique des émotions",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 42,
    "description": "Psychopathologie des émotions Les émotions sont une gêne, un fardeau… Pas du tout ! Les émotions, c’est la vie ! Ah oui ? Avoir la gorge nouée, le cœur battant, les mains moites Se sentir joyeux, amoureux… Ruminer sa colère, être rongé d’envie… Enthousiaste, tendre… Soucieux,…",
    "themes": [
      "Émotions",
      "Clinique"
    ],
    "keywords": [
      "CM08 — Psychopathologie des émotions",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/CLINIQUE DES EMOTIONS/CM08 - Psychopathologie des émotions.docx",
      "CM — Clinique des émotions",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique des émotions",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/clinique-des-emotions/cm08-psychopathologie-des-emotions.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-clinique-des-emotions-cm08-psychopathologie-des-emotions"
  },
  {
    "id": "cours:psy-l2-s4-ue6-clinique-des-emotions-cm09-la-colere",
    "slug": "cm09-la-colere.md",
    "title": "CM09 — La colère",
    "module": "CM — Clinique des émotions",
    "courseTheme": "clinique",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 43,
    "description": "La colère La colère Colère état trait, colère au volant et trouble de colère Introduction Colère état trait Colère éprouvé au volant La colère On peut avoir quelques situations pour engendrer la colère : juste au moment où vous allez vous garer, quelqu’un vous double et prend la…",
    "themes": [
      "Émotions",
      "Clinique"
    ],
    "keywords": [
      "CM09 — La colère",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/CLINIQUE DES EMOTIONS/CM09 - La colère.docx",
      "CM — Clinique des émotions",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Clinique des émotions",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/clinique-des-emotions/cm09-la-colere.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-clinique-des-emotions-cm09-la-colere"
  },
  {
    "id": "cours:psy-l2-s4-ue6-psychologie-evolutionniste-cm01-02-epistemologie-de-la-psychologie-evolutionniste",
    "slug": "cm01-02-epistemologie-de-la-psychologie-evolutionniste.md",
    "title": "CM01-02 — Epistémologie de la psychologie évolutionniste",
    "module": "CM — Psychologie évolutionniste",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 44,
    "description": "Epistémologie de la psychologie évolutionniste La psychologie est apparue après la seconde guerre mondiale, avant dans le monde anglo saxon. Elle est marquée par des courants de pensée idéologique, épistémologique philosophique La psychologie évolutionniste a eu du mal à s’intégrer.…",
    "themes": [
      "Évolution",
      "Éthologie"
    ],
    "keywords": [
      "CM01-02 — Epistémologie de la psychologie évolutionniste",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/EVOLUTIONNISTE/CM01-02 - Epistémologie de la psychologie évolutionniste.docx",
      "CM — Psychologie évolutionniste",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie évolutionniste",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/psychologie-evolutionniste/cm01-02-epistemologie-de-la-psychologie-evolutionniste.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-psychologie-evolutionniste-cm01-02-epistemologie-de-la-psychologie-evolutionniste"
  },
  {
    "id": "cours:psy-l2-s4-ue6-psychologie-evolutionniste-cm03-05-elements-de-sociobiologie-et-ecologie-comportementale",
    "slug": "cm03-05-elements-de-sociobiologie-et-ecologie-comportementale.md",
    "title": "CM03-05 — Eléments de sociobiologie & écologie comportementale",
    "module": "CM — Psychologie évolutionniste",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 45,
    "description": "Eléments de sociobiologie & écologie comportementale Behavioral ecology et la théorie des jeux (game theory) Episémologie La théorie des jeux n’est pas une théorie en soi. C’est une famille mathématique étudier pour formaliser les jeux (en particulier pour les échecs). Il a fallu…",
    "themes": [
      "Évolution",
      "Éthologie"
    ],
    "keywords": [
      "CM03-05 — Eléments de sociobiologie & écologie comportementale",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/EVOLUTIONNISTE/CM03-05 - Eléments de sociobiologie & écologie comportementale.docx",
      "CM — Psychologie évolutionniste",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie évolutionniste",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/psychologie-evolutionniste/cm03-05-elements-de-sociobiologie-et-ecologie-comportementale.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-psychologie-evolutionniste-cm03-05-elements-de-sociobiologie-et-ecologie-comportementale"
  },
  {
    "id": "cours:psy-l2-s4-ue6-psychologie-evolutionniste-cm05-07-organes-mentaux-et-pathologies",
    "slug": "cm05-07-organes-mentaux-et-pathologies.md",
    "title": "CM05-07 — Organes mentaux et pathologies",
    "module": "CM — Psychologie évolutionniste",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 46,
    "description": "Organes mentaux (et pathologies) EEA (Environnement of Evolutionary Adaptedness (Tooby & Cosmides) Principe Calendrier préhistorique (et historique) Primates 100 000 000 Chimpanzé – Humain · Séparé · Homo Habilis · Homo Sapiens 3 – 6 000 000 · 1 400 000 · 700 000 · 100 000 Idaltu ·…",
    "themes": [
      "Évolution",
      "Éthologie"
    ],
    "keywords": [
      "CM05-07 — Organes mentaux et pathologies",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/EVOLUTIONNISTE/CM05-07 - Organes mentaux et pathologies.docx",
      "CM — Psychologie évolutionniste",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie évolutionniste",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/psychologie-evolutionniste/cm05-07-organes-mentaux-et-pathologies.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-psychologie-evolutionniste-cm05-07-organes-mentaux-et-pathologies"
  },
  {
    "id": "cours:psy-l2-s4-ue6-psychologie-evolutionniste-cm08-notions-d-ethologie-humaine",
    "slug": "cm08-notions-d-ethologie-humaine.md",
    "title": "CM08 — Notions d éthologie humaine",
    "module": "CM — Psychologie évolutionniste",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 47,
    "description": "Notions d’éthologie humaine La vision zoomorphique Principe Anthropomorphisme : tendance à concevoir les divinités ou les animaux à l’image des hommes et à leur prêter de ce fait des comportements humains. Desmond Morris a écrit plusieurs best sellers comme Le singe nu ou le zoo…",
    "themes": [
      "Évolution",
      "Éthologie"
    ],
    "keywords": [
      "CM08 — Notions d éthologie humaine",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/EVOLUTIONNISTE/CM08 - Notions d éthologie humaine.docx",
      "CM — Psychologie évolutionniste",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie évolutionniste",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/psychologie-evolutionniste/cm08-notions-d-ethologie-humaine.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-psychologie-evolutionniste-cm08-notions-d-ethologie-humaine"
  },
  {
    "id": "cours:psy-l2-s4-ue6-psychologie-evolutionniste-cm09-10-traits-d-histoire-de-vie-et-investissement-reproducteur",
    "slug": "cm09-10-traits-d-histoire-de-vie-et-investissement-reproducteur.md",
    "title": "CM09-10 — Traits d histoire de vie & investissement reproducteur",
    "module": "CM — Psychologie évolutionniste",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 48,
    "description": "Traits d’histoire de vie & investissement reproducteur Principe d’allocation de ressource Ressources Allocations Compromis : Trade off L’investissement parental ou reproducteur (TRIVERS, 1974) Définition Modèles évolutifs r & k Investissement et potentiel maternels La ménopause…",
    "themes": [
      "Évolution",
      "Éthologie"
    ],
    "keywords": [
      "CM09-10 — Traits d histoire de vie & investissement reproducteur",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/EVOLUTIONNISTE/CM09-10 - Traits d histoire de vie & investissement reproducteur.docx",
      "CM — Psychologie évolutionniste",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie évolutionniste",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/psychologie-evolutionniste/cm09-10-traits-d-histoire-de-vie-et-investissement-reproducteur.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-psychologie-evolutionniste-cm09-10-traits-d-histoire-de-vie-et-investissement-reproducteur"
  },
  {
    "id": "cours:psy-l2-s4-ue6-psychologie-evolutionniste-cm10-12-interpretation-evolutive",
    "slug": "cm10-12-interpretation-evolutive.md",
    "title": "CM10-12 — Interprétation évolutive",
    "module": "CM — Psychologie évolutionniste",
    "courseTheme": "developpement",
    "sourceType": "Prise de notes personnelle",
    "format": "Notes de cours",
    "sequence": 49,
    "description": "Interprétation évolutive & adaptative des comportements sexuels Principe généraux sur la reproduction sexuée Reproduction sexuée La reproduction sexuée n’est pas le seul mode de reproduction. La caractéristique de cette reproduction représente un avantage/ gain = la diversité. Si une…",
    "themes": [
      "Évolution",
      "Éthologie"
    ],
    "keywords": [
      "CM10-12 — Interprétation évolutive",
      "UE6 - OUVERTURE PSYCHOLOGIQUE/EVOLUTIONNISTE/CM10-12 - Interprétation évolutive.docx",
      "CM — Psychologie évolutionniste",
      "UE6 — Ouverture psychologique",
      "Prise de notes personnelle"
    ],
    "kind": "cours",
    "formation": "Psychologie",
    "degree": "Licence",
    "year": "L2",
    "semester": "Semestre 4",
    "ue": "UE6 — Ouverture psychologique",
    "domain": "psycho",
    "people": [],
    "source": "Cours universitaires — S4",
    "subject": "CM — Psychologie évolutionniste",
    "contentUrl": "/mediatheque/cours/contenus/psycho/l2/s4/ue6/psychologie-evolutionniste/cm10-12-interpretation-evolutive.md",
    "url": "/mediatheque/cours/?id=psy-l2-s4-ue6-psychologie-evolutionniste-cm10-12-interpretation-evolutive"
  }
];
  const norm = (v="") => String(v).replace(/\/+$/, "");
  const ids = new Set(DATA.resources.map(x => x && x.id).filter(Boolean));
  const urls = new Set(DATA.resources.map(x => norm(x && x.contentUrl || "")).filter(Boolean));
  let added = 0;
  incoming.forEach(item => {
    if (!item || ids.has(item.id) || urls.has(norm(item.contentUrl))) return;
    DATA.resources.push(item); ids.add(item.id); urls.add(norm(item.contentUrl)); added += 1;
  });
  window.FV_S4_COURSES_STATUS = { ok: true, added, supplied: incoming.length };

  if (!window.__FV_S4_FETCH_PATCHED) {
    window.__FV_S4_FETCH_PATCHED = true;
    const nativeFetch = window.fetch.bind(window);
    const scriptUrl = (document.currentScript && document.currentScript.src) || location.href;
    const extraIndexUrl = new URL('./cours/s4-search-index.json', scriptUrl).href;
    window.fetch = async function(input, init) {
      let url = '';
      try { url = typeof input === 'string' ? new URL(input, location.href).href : new URL(input.url, location.href).href; } catch (_) {}
      if (!/\/mediatheque\/cours\/search-index\.json(?:[?#]|$)/.test(url)) return nativeFetch(input, init);
      const [baseResponse, extraResponse] = await Promise.all([
        nativeFetch(input, init).catch(() => null),
        nativeFetch(extraIndexUrl, { cache:'no-store', credentials:'same-origin' }).catch(() => null)
      ]);
      let base={}, extra={};
      try { if (baseResponse && baseResponse.ok) base=await baseResponse.clone().json(); } catch (_) {}
      try { if (extraResponse && extraResponse.ok) extra=await extraResponse.json(); } catch (_) {}
      return new Response(JSON.stringify({ ...base, ...extra }), { status:200, headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'} });
    };
  }
})();
